var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

// src/app.ts
import express7 from "express";
import cors from "cors";
import { toNodeHandler } from "better-auth/node";

// src/lib/auth.ts
import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";

// generated/prisma/client.ts
import * as path from "path";
import { fileURLToPath } from "url";

// generated/prisma/internal/class.ts
import * as runtime from "@prisma/client/runtime/client";
var config = {
  "previewFeatures": [],
  "clientVersion": "7.4.0",
  "engineVersion": "ab56fe763f921d033a6c195e7ddeb3e255bdbb57",
  "activeProvider": "postgresql",
  "inlineSchema": '// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\n// Looking for ways to speed up your queries, or scale easily with your serverless or edge functions?\n// Try Prisma Accelerate: https://pris.ly/cli/accelerate-init\n\ngenerator client {\n  provider = "prisma-client"\n  output   = "../generated/prisma"\n}\n\ndatasource db {\n  provider = "postgresql"\n}\n\nmodel User {\n  id        String     @id @default(uuid())\n  name      String\n  email     String     @unique\n  role      Role       @default(CUSTOMER)\n  status    UserStatus @default(ACTIVE)\n  createdAt DateTime   @default(now())\n\n  // Relations\n  medicines Medicine[] @relation("SellerMedicines")\n  orders    Order[]\n  reviews   Review[]\n  cartItems Cart[]\n\n  emailVerified Boolean   @default(false)\n  image         String?\n  updatedAt     DateTime  @updatedAt\n  sessions      Session[]\n  accounts      Account[]\n\n  @@map("users")\n}\n\n//medicine \n\nmodel Medicine {\n  id          String   @id @default(uuid())\n  name        String\n  price       Float\n  stock       Int\n  description String\n  image       String?\n  createdAt   DateTime @default(now())\n\n  categoryId String\n  sellerId   String\n\n  // Relations\n  category Category @relation(fields: [categoryId], references: [id])\n  seller   User     @relation("SellerMedicines", fields: [sellerId], references: [id], onDelete: Cascade)\n\n  orderItems OrderItem[]\n  reviews    Review[]\n  carts      Cart[]\n\n  @@map("medicines")\n}\n\n//category \n\nmodel Category {\n  id        String   @id @default(uuid())\n  name      String   @unique\n  createdAt DateTime @default(now())\n\n  medicines Medicine[]\n\n  @@map("categories")\n}\n\n//CART MODEL\n\nmodel Cart {\n  id         String @id @default(uuid())\n  userId     String\n  medicineId String\n  quantity   Int\n\n  // Relations\n  user     User     @relation(fields: [userId], references: [id])\n  medicine Medicine @relation(fields: [medicineId], references: [id])\n\n  @@unique([userId, medicineId])\n  @@map("cart")\n}\n\n// ORDER MODEL\n\nmodel Order {\n  id            String        @id @default(uuid())\n  userId        String\n  status        OrderStatus   @default(PLACED)\n  paymentMethod PaymentMethod @default(CASH_ON_DELIVERY)\n  paymentStatus PaymentStatus @default(PENDING)\n  address       String\n  createdAt     DateTime      @default(now())\n\n  // Relations\n  user       User        @relation(fields: [userId], references: [id])\n  orderItems OrderItem[]\n\n  @@map("orders")\n}\n\nenum PaymentMethod {\n  CASH_ON_DELIVERY\n  ONLINE\n}\n\nenum PaymentStatus {\n  PENDING\n  PAID\n  FAILED\n}\n\n//ORDER ITEM MODEL\n\nmodel OrderItem {\n  id         String @id @default(uuid())\n  orderId    String\n  medicineId String\n  price      Float\n  quantity   Int\n\n  // Relations\n  order    Order    @relation(fields: [orderId], references: [id])\n  medicine Medicine @relation(fields: [medicineId], references: [id])\n\n  @@map("order_items")\n}\n\n//REVIEW MODEL\n\nmodel Review {\n  id         String   @id @default(uuid())\n  userId     String\n  medicineId String\n  rating     Int\n  comment    String\n  createdAt  DateTime @default(now())\n\n  // Relations\n  user     User     @relation(fields: [userId], references: [id])\n  medicine Medicine @relation(fields: [medicineId], references: [id])\n\n  @@unique([userId, medicineId])\n  @@map("reviews")\n}\n\n//ENUMS \nenum Role {\n  CUSTOMER\n  SELLER\n  ADMIN\n}\n\nenum UserStatus {\n  ACTIVE\n  BANNED\n}\n\nenum OrderStatus {\n  PLACED\n  PROCESSING\n  SHIPPED\n  DELIVERED\n  CANCELLED\n}\n\nmodel Session {\n  id        String   @id\n  expiresAt DateTime\n  token     String\n  createdAt DateTime @default(now())\n  updatedAt DateTime @updatedAt\n  ipAddress String?\n  userAgent String?\n  userId    String\n  user      User     @relation(fields: [userId], references: [id], onDelete: Cascade)\n\n  @@unique([token])\n  @@index([userId])\n  @@map("session")\n}\n\nmodel Account {\n  id                    String    @id\n  accountId             String\n  providerId            String\n  userId                String\n  user                  User      @relation(fields: [userId], references: [id], onDelete: Cascade)\n  accessToken           String?\n  refreshToken          String?\n  idToken               String?\n  accessTokenExpiresAt  DateTime?\n  refreshTokenExpiresAt DateTime?\n  scope                 String?\n  password              String?\n  createdAt             DateTime  @default(now())\n  updatedAt             DateTime  @updatedAt\n\n  @@index([userId])\n  @@map("account")\n}\n\nmodel Verification {\n  id         String   @id\n  identifier String\n  value      String\n  expiresAt  DateTime\n  createdAt  DateTime @default(now())\n  updatedAt  DateTime @updatedAt\n\n  @@index([identifier])\n  @@map("verification")\n}\n',
  "runtimeDataModel": {
    "models": {},
    "enums": {},
    "types": {}
  },
  "parameterizationSchema": {
    "strings": [],
    "graph": ""
  }
};
config.runtimeDataModel = JSON.parse('{"models":{"User":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"email","kind":"scalar","type":"String"},{"name":"role","kind":"enum","type":"Role"},{"name":"status","kind":"enum","type":"UserStatus"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"medicines","kind":"object","type":"Medicine","relationName":"SellerMedicines"},{"name":"orders","kind":"object","type":"Order","relationName":"OrderToUser"},{"name":"reviews","kind":"object","type":"Review","relationName":"ReviewToUser"},{"name":"cartItems","kind":"object","type":"Cart","relationName":"CartToUser"},{"name":"emailVerified","kind":"scalar","type":"Boolean"},{"name":"image","kind":"scalar","type":"String"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"sessions","kind":"object","type":"Session","relationName":"SessionToUser"},{"name":"accounts","kind":"object","type":"Account","relationName":"AccountToUser"}],"dbName":"users"},"Medicine":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"stock","kind":"scalar","type":"Int"},{"name":"description","kind":"scalar","type":"String"},{"name":"image","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"categoryId","kind":"scalar","type":"String"},{"name":"sellerId","kind":"scalar","type":"String"},{"name":"category","kind":"object","type":"Category","relationName":"CategoryToMedicine"},{"name":"seller","kind":"object","type":"User","relationName":"SellerMedicines"},{"name":"orderItems","kind":"object","type":"OrderItem","relationName":"MedicineToOrderItem"},{"name":"reviews","kind":"object","type":"Review","relationName":"MedicineToReview"},{"name":"carts","kind":"object","type":"Cart","relationName":"CartToMedicine"}],"dbName":"medicines"},"Category":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"medicines","kind":"object","type":"Medicine","relationName":"CategoryToMedicine"}],"dbName":"categories"},"Cart":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"medicineId","kind":"scalar","type":"String"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"user","kind":"object","type":"User","relationName":"CartToUser"},{"name":"medicine","kind":"object","type":"Medicine","relationName":"CartToMedicine"}],"dbName":"cart"},"Order":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"status","kind":"enum","type":"OrderStatus"},{"name":"paymentMethod","kind":"enum","type":"PaymentMethod"},{"name":"paymentStatus","kind":"enum","type":"PaymentStatus"},{"name":"address","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"OrderToUser"},{"name":"orderItems","kind":"object","type":"OrderItem","relationName":"OrderToOrderItem"}],"dbName":"orders"},"OrderItem":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"orderId","kind":"scalar","type":"String"},{"name":"medicineId","kind":"scalar","type":"String"},{"name":"price","kind":"scalar","type":"Float"},{"name":"quantity","kind":"scalar","type":"Int"},{"name":"order","kind":"object","type":"Order","relationName":"OrderToOrderItem"},{"name":"medicine","kind":"object","type":"Medicine","relationName":"MedicineToOrderItem"}],"dbName":"order_items"},"Review":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"medicineId","kind":"scalar","type":"String"},{"name":"rating","kind":"scalar","type":"Int"},{"name":"comment","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"user","kind":"object","type":"User","relationName":"ReviewToUser"},{"name":"medicine","kind":"object","type":"Medicine","relationName":"MedicineToReview"}],"dbName":"reviews"},"Session":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"token","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"},{"name":"ipAddress","kind":"scalar","type":"String"},{"name":"userAgent","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"SessionToUser"}],"dbName":"session"},"Account":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"accountId","kind":"scalar","type":"String"},{"name":"providerId","kind":"scalar","type":"String"},{"name":"userId","kind":"scalar","type":"String"},{"name":"user","kind":"object","type":"User","relationName":"AccountToUser"},{"name":"accessToken","kind":"scalar","type":"String"},{"name":"refreshToken","kind":"scalar","type":"String"},{"name":"idToken","kind":"scalar","type":"String"},{"name":"accessTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"refreshTokenExpiresAt","kind":"scalar","type":"DateTime"},{"name":"scope","kind":"scalar","type":"String"},{"name":"password","kind":"scalar","type":"String"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"account"},"Verification":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"identifier","kind":"scalar","type":"String"},{"name":"value","kind":"scalar","type":"String"},{"name":"expiresAt","kind":"scalar","type":"DateTime"},{"name":"createdAt","kind":"scalar","type":"DateTime"},{"name":"updatedAt","kind":"scalar","type":"DateTime"}],"dbName":"verification"}},"enums":{},"types":{}}');
config.parameterizationSchema = {
  strings: JSON.parse('["where","orderBy","cursor","medicines","_count","category","seller","user","orderItems","order","medicine","reviews","carts","orders","cartItems","sessions","accounts","User.findUnique","User.findUniqueOrThrow","User.findFirst","User.findFirstOrThrow","User.findMany","data","User.createOne","User.createMany","User.createManyAndReturn","User.updateOne","User.updateMany","User.updateManyAndReturn","create","update","User.upsertOne","User.deleteOne","User.deleteMany","having","_min","_max","User.groupBy","User.aggregate","Medicine.findUnique","Medicine.findUniqueOrThrow","Medicine.findFirst","Medicine.findFirstOrThrow","Medicine.findMany","Medicine.createOne","Medicine.createMany","Medicine.createManyAndReturn","Medicine.updateOne","Medicine.updateMany","Medicine.updateManyAndReturn","Medicine.upsertOne","Medicine.deleteOne","Medicine.deleteMany","_avg","_sum","Medicine.groupBy","Medicine.aggregate","Category.findUnique","Category.findUniqueOrThrow","Category.findFirst","Category.findFirstOrThrow","Category.findMany","Category.createOne","Category.createMany","Category.createManyAndReturn","Category.updateOne","Category.updateMany","Category.updateManyAndReturn","Category.upsertOne","Category.deleteOne","Category.deleteMany","Category.groupBy","Category.aggregate","Cart.findUnique","Cart.findUniqueOrThrow","Cart.findFirst","Cart.findFirstOrThrow","Cart.findMany","Cart.createOne","Cart.createMany","Cart.createManyAndReturn","Cart.updateOne","Cart.updateMany","Cart.updateManyAndReturn","Cart.upsertOne","Cart.deleteOne","Cart.deleteMany","Cart.groupBy","Cart.aggregate","Order.findUnique","Order.findUniqueOrThrow","Order.findFirst","Order.findFirstOrThrow","Order.findMany","Order.createOne","Order.createMany","Order.createManyAndReturn","Order.updateOne","Order.updateMany","Order.updateManyAndReturn","Order.upsertOne","Order.deleteOne","Order.deleteMany","Order.groupBy","Order.aggregate","OrderItem.findUnique","OrderItem.findUniqueOrThrow","OrderItem.findFirst","OrderItem.findFirstOrThrow","OrderItem.findMany","OrderItem.createOne","OrderItem.createMany","OrderItem.createManyAndReturn","OrderItem.updateOne","OrderItem.updateMany","OrderItem.updateManyAndReturn","OrderItem.upsertOne","OrderItem.deleteOne","OrderItem.deleteMany","OrderItem.groupBy","OrderItem.aggregate","Review.findUnique","Review.findUniqueOrThrow","Review.findFirst","Review.findFirstOrThrow","Review.findMany","Review.createOne","Review.createMany","Review.createManyAndReturn","Review.updateOne","Review.updateMany","Review.updateManyAndReturn","Review.upsertOne","Review.deleteOne","Review.deleteMany","Review.groupBy","Review.aggregate","Session.findUnique","Session.findUniqueOrThrow","Session.findFirst","Session.findFirstOrThrow","Session.findMany","Session.createOne","Session.createMany","Session.createManyAndReturn","Session.updateOne","Session.updateMany","Session.updateManyAndReturn","Session.upsertOne","Session.deleteOne","Session.deleteMany","Session.groupBy","Session.aggregate","Account.findUnique","Account.findUniqueOrThrow","Account.findFirst","Account.findFirstOrThrow","Account.findMany","Account.createOne","Account.createMany","Account.createManyAndReturn","Account.updateOne","Account.updateMany","Account.updateManyAndReturn","Account.upsertOne","Account.deleteOne","Account.deleteMany","Account.groupBy","Account.aggregate","Verification.findUnique","Verification.findUniqueOrThrow","Verification.findFirst","Verification.findFirstOrThrow","Verification.findMany","Verification.createOne","Verification.createMany","Verification.createManyAndReturn","Verification.updateOne","Verification.updateMany","Verification.updateManyAndReturn","Verification.upsertOne","Verification.deleteOne","Verification.deleteMany","Verification.groupBy","Verification.aggregate","AND","OR","NOT","id","identifier","value","expiresAt","createdAt","updatedAt","equals","in","notIn","lt","lte","gt","gte","not","contains","startsWith","endsWith","accountId","providerId","userId","accessToken","refreshToken","idToken","accessTokenExpiresAt","refreshTokenExpiresAt","scope","password","token","ipAddress","userAgent","medicineId","rating","comment","orderId","price","quantity","OrderStatus","status","PaymentMethod","paymentMethod","PaymentStatus","paymentStatus","address","name","every","some","none","stock","description","image","categoryId","sellerId","email","Role","role","UserStatus","emailVerified","userId_medicineId","is","isNot","connectOrCreate","upsert","createMany","set","disconnect","delete","connect","updateMany","deleteMany","increment","decrement","multiply","divide"]'),
  graph: "hgVdoAESAwAAuQIAIAsAAMsCACANAADKAgAgDgAAzAIAIA8AAM0CACAQAADOAgAguQEAAMUCADC6AQAALwAQuwEAAMUCADC8AQEAAAABwAFAAJsCACHBAUAAmwIAIeEBAADHAvQBIucBAQCaAgAh7QEBAMkCACHwAQEAAAAB8gEAAMYC8gEi9AEgAMgCACEBAAAAAQAgEQUAAOICACAGAADRAgAgCAAA1wIAIAsAAMsCACAMAADMAgAguQEAAOECADC6AQAAAwAQuwEAAOECADC8AQEAmgIAIcABQACbAgAh3gEIAN8CACHnAQEAmgIAIesBAgDaAgAh7AEBAJoCACHtAQEAyQIAIe4BAQCaAgAh7wEBAJoCACEGBQAAxAQAIAYAAMAEACAIAADBBAAgCwAAvAQAIAwAAL0EACDtAQAA6AIAIBEFAADiAgAgBgAA0QIAIAgAANcCACALAADLAgAgDAAAzAIAILkBAADhAgAwugEAAAMAELsBAADhAgAwvAEBAAAAAcABQACbAgAh3gEIAN8CACHnAQEAmgIAIesBAgDaAgAh7AEBAJoCACHtAQEAyQIAIe4BAQCaAgAh7wEBAJoCACEDAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIAEAAAADACAKCQAA4AIAIAoAANsCACC5AQAA3gIAMLoBAAAJABC7AQAA3gIAMLwBAQCaAgAh2gEBAJoCACHdAQEAmgIAId4BCADfAgAh3wECANoCACECCQAAwwQAIAoAAMIEACAKCQAA4AIAIAoAANsCACC5AQAA3gIAMLoBAAAJABC7AQAA3gIAMLwBAQAAAAHaAQEAmgIAId0BAQCaAgAh3gEIAN8CACHfAQIA2gIAIQMAAAAJACABAAAKADACAAALACADAAAACQAgAQAACgAwAgAACwAgAQAAAAkAIAsHAADRAgAgCgAA2wIAILkBAADdAgAwugEAAA8AELsBAADdAgAwvAEBAJoCACHAAUAAmwIAIc8BAQCaAgAh2gEBAJoCACHbAQIA2gIAIdwBAQCaAgAhAgcAAMAEACAKAADCBAAgDAcAANECACAKAADbAgAguQEAAN0CADC6AQAADwAQuwEAAN0CADC8AQEAAAABwAFAAJsCACHPAQEAmgIAIdoBAQCaAgAh2wECANoCACHcAQEAmgIAIfUBAADcAgAgAwAAAA8AIAEAABAAMAIAABEAIAkHAADRAgAgCgAA2wIAILkBAADZAgAwugEAABMAELsBAADZAgAwvAEBAJoCACHPAQEAmgIAIdoBAQCaAgAh3wECANoCACECBwAAwAQAIAoAAMIEACAKBwAA0QIAIAoAANsCACC5AQAA2QIAMLoBAAATABC7AQAA2QIAMLwBAQAAAAHPAQEAmgIAIdoBAQCaAgAh3wECANoCACH1AQAA2AIAIAMAAAATACABAAAUADACAAAVACABAAAACQAgAQAAAA8AIAEAAAATACAMBwAA0QIAIAgAANcCACC5AQAA0wIAMLoBAAAaABC7AQAA0wIAMLwBAQCaAgAhwAFAAJsCACHPAQEAmgIAIeEBAADUAuEBIuMBAADVAuMBIuUBAADWAuUBIuYBAQCaAgAhAgcAAMAEACAIAADBBAAgDAcAANECACAIAADXAgAguQEAANMCADC6AQAAGgAQuwEAANMCADC8AQEAAAABwAFAAJsCACHPAQEAmgIAIeEBAADUAuEBIuMBAADVAuMBIuUBAADWAuUBIuYBAQCaAgAhAwAAABoAIAEAABsAMAIAABwAIAMAAAAPACABAAAQADACAAARACADAAAAEwAgAQAAFAAwAgAAFQAgDAcAANECACC5AQAA0gIAMLoBAAAgABC7AQAA0gIAMLwBAQCaAgAhvwFAAJsCACHAAUAAmwIAIcEBQACbAgAhzwEBAJoCACHXAQEAmgIAIdgBAQDJAgAh2QEBAMkCACEDBwAAwAQAINgBAADoAgAg2QEAAOgCACAMBwAA0QIAILkBAADSAgAwugEAACAAELsBAADSAgAwvAEBAAAAAb8BQACbAgAhwAFAAJsCACHBAUAAmwIAIc8BAQCaAgAh1wEBAAAAAdgBAQDJAgAh2QEBAMkCACEDAAAAIAAgAQAAIQAwAgAAIgAgEQcAANECACC5AQAAzwIAMLoBAAAkABC7AQAAzwIAMLwBAQCaAgAhwAFAAJsCACHBAUAAmwIAIc0BAQCaAgAhzgEBAJoCACHPAQEAmgIAIdABAQDJAgAh0QEBAMkCACHSAQEAyQIAIdMBQADQAgAh1AFAANACACHVAQEAyQIAIdYBAQDJAgAhCAcAAMAEACDQAQAA6AIAINEBAADoAgAg0gEAAOgCACDTAQAA6AIAINQBAADoAgAg1QEAAOgCACDWAQAA6AIAIBEHAADRAgAguQEAAM8CADC6AQAAJAAQuwEAAM8CADC8AQEAAAABwAFAAJsCACHBAUAAmwIAIc0BAQCaAgAhzgEBAJoCACHPAQEAmgIAIdABAQDJAgAh0QEBAMkCACHSAQEAyQIAIdMBQADQAgAh1AFAANACACHVAQEAyQIAIdYBAQDJAgAhAwAAACQAIAEAACUAMAIAACYAIAEAAAADACABAAAAGgAgAQAAAA8AIAEAAAATACABAAAAIAAgAQAAACQAIAEAAAABACASAwAAuQIAIAsAAMsCACANAADKAgAgDgAAzAIAIA8AAM0CACAQAADOAgAguQEAAMUCADC6AQAALwAQuwEAAMUCADC8AQEAmgIAIcABQACbAgAhwQFAAJsCACHhAQAAxwL0ASLnAQEAmgIAIe0BAQDJAgAh8AEBAJoCACHyAQAAxgLyASL0ASAAyAIAIQcDAADiAwAgCwAAvAQAIA0AALsEACAOAAC9BAAgDwAAvgQAIBAAAL8EACDtAQAA6AIAIAMAAAAvACABAAAwADACAAABACADAAAALwAgAQAAMAAwAgAAAQAgAwAAAC8AIAEAADAAMAIAAAEAIA8DAAC1BAAgCwAAtwQAIA0AALYEACAOAAC4BAAgDwAAuQQAIBAAALoEACC8AQEAAAABwAFAAAAAAcEBQAAAAAHhAQAAAPQBAucBAQAAAAHtAQEAAAAB8AEBAAAAAfIBAAAA8gEC9AEgAAAAAQEWAAA0ACAJvAEBAAAAAcABQAAAAAHBAUAAAAAB4QEAAAD0AQLnAQEAAAAB7QEBAAAAAfABAQAAAAHyAQAAAPIBAvQBIAAAAAEBFgAANgAwARYAADYAMA8DAADwAwAgCwAA8gMAIA0AAPEDACAOAADzAwAgDwAA9AMAIBAAAPUDACC8AQEA5gIAIcABQADnAgAhwQFAAOcCACHhAQAA7gP0ASLnAQEA5gIAIe0BAQDsAgAh8AEBAOYCACHyAQAA7QPyASL0ASAA7wMAIQIAAAABACAWAAA5ACAJvAEBAOYCACHAAUAA5wIAIcEBQADnAgAh4QEAAO4D9AEi5wEBAOYCACHtAQEA7AIAIfABAQDmAgAh8gEAAO0D8gEi9AEgAO8DACECAAAALwAgFgAAOwAgAgAAAC8AIBYAADsAIAMAAAABACAdAAA0ACAeAAA5ACABAAAAAQAgAQAAAC8AIAQEAADqAwAgIwAA7AMAICQAAOsDACDtAQAA6AIAIAy5AQAAuwIAMLoBAABCABC7AQAAuwIAMLwBAQCSAgAhwAFAAJMCACHBAUAAkwIAIeEBAAC9AvQBIucBAQCSAgAh7QEBAJ0CACHwAQEAkgIAIfIBAAC8AvIBIvQBIAC-AgAhAwAAAC8AIAEAAEEAMCIAAEIAIAMAAAAvACABAAAwADACAAABACABAAAABQAgAQAAAAUAIAMAAAADACABAAAEADACAAAFACADAAAAAwAgAQAABAAwAgAABQAgAwAAAAMAIAEAAAQAMAIAAAUAIA4FAADpAwAgBgAA3QMAIAgAAN4DACALAADfAwAgDAAA4AMAILwBAQAAAAHAAUAAAAAB3gEIAAAAAecBAQAAAAHrAQIAAAAB7AEBAAAAAe0BAQAAAAHuAQEAAAAB7wEBAAAAAQEWAABKACAJvAEBAAAAAcABQAAAAAHeAQgAAAAB5wEBAAAAAesBAgAAAAHsAQEAAAAB7QEBAAAAAe4BAQAAAAHvAQEAAAABARYAAEwAMAEWAABMADAOBQAA6AMAIAYAALcDACAIAAC4AwAgCwAAuQMAIAwAALoDACC8AQEA5gIAIcABQADnAgAh3gEIAIQDACHnAQEA5gIAIesBAgD6AgAh7AEBAOYCACHtAQEA7AIAIe4BAQDmAgAh7wEBAOYCACECAAAABQAgFgAATwAgCbwBAQDmAgAhwAFAAOcCACHeAQgAhAMAIecBAQDmAgAh6wECAPoCACHsAQEA5gIAIe0BAQDsAgAh7gEBAOYCACHvAQEA5gIAIQIAAAADACAWAABRACACAAAAAwAgFgAAUQAgAwAAAAUAIB0AAEoAIB4AAE8AIAEAAAAFACABAAAAAwAgBgQAAOMDACAjAADmAwAgJAAA5QMAIDUAAOQDACA2AADnAwAg7QEAAOgCACAMuQEAALoCADC6AQAAWAAQuwEAALoCADC8AQEAkgIAIcABQACTAgAh3gEIAKoCACHnAQEAkgIAIesBAgCmAgAh7AEBAJICACHtAQEAnQIAIe4BAQCSAgAh7wEBAJICACEDAAAAAwAgAQAAVwAwIgAAWAAgAwAAAAMAIAEAAAQAMAIAAAUAIAcDAAC5AgAguQEAALgCADC6AQAAXgAQuwEAALgCADC8AQEAAAABwAFAAJsCACHnAQEAAAABAQAAAFsAIAEAAABbACAHAwAAuQIAILkBAAC4AgAwugEAAF4AELsBAAC4AgAwvAEBAJoCACHAAUAAmwIAIecBAQCaAgAhAQMAAOIDACADAAAAXgAgAQAAXwAwAgAAWwAgAwAAAF4AIAEAAF8AMAIAAFsAIAMAAABeACABAABfADACAABbACAEAwAA4QMAILwBAQAAAAHAAUAAAAAB5wEBAAAAAQEWAABjACADvAEBAAAAAcABQAAAAAHnAQEAAAABARYAAGUAMAEWAABlADAEAwAAqwMAILwBAQDmAgAhwAFAAOcCACHnAQEA5gIAIQIAAABbACAWAABoACADvAEBAOYCACHAAUAA5wIAIecBAQDmAgAhAgAAAF4AIBYAAGoAIAIAAABeACAWAABqACADAAAAWwAgHQAAYwAgHgAAaAAgAQAAAFsAIAEAAABeACADBAAAqAMAICMAAKoDACAkAACpAwAgBrkBAAC3AgAwugEAAHEAELsBAAC3AgAwvAEBAJICACHAAUAAkwIAIecBAQCSAgAhAwAAAF4AIAEAAHAAMCIAAHEAIAMAAABeACABAABfADACAABbACABAAAAFQAgAQAAABUAIAMAAAATACABAAAUADACAAAVACADAAAAEwAgAQAAFAAwAgAAFQAgAwAAABMAIAEAABQAMAIAABUAIAYHAACmAwAgCgAApwMAILwBAQAAAAHPAQEAAAAB2gEBAAAAAd8BAgAAAAEBFgAAeQAgBLwBAQAAAAHPAQEAAAAB2gEBAAAAAd8BAgAAAAEBFgAAewAwARYAAHsAMAYHAACkAwAgCgAApQMAILwBAQDmAgAhzwEBAOYCACHaAQEA5gIAId8BAgD6AgAhAgAAABUAIBYAAH4AIAS8AQEA5gIAIc8BAQDmAgAh2gEBAOYCACHfAQIA-gIAIQIAAAATACAWAACAAQAgAgAAABMAIBYAAIABACADAAAAFQAgHQAAeQAgHgAAfgAgAQAAABUAIAEAAAATACAFBAAAnwMAICMAAKIDACAkAAChAwAgNQAAoAMAIDYAAKMDACAHuQEAALYCADC6AQAAhwEAELsBAAC2AgAwvAEBAJICACHPAQEAkgIAIdoBAQCSAgAh3wECAKYCACEDAAAAEwAgAQAAhgEAMCIAAIcBACADAAAAEwAgAQAAFAAwAgAAFQAgAQAAABwAIAEAAAAcACADAAAAGgAgAQAAGwAwAgAAHAAgAwAAABoAIAEAABsAMAIAABwAIAMAAAAaACABAAAbADACAAAcACAJBwAAnQMAIAgAAJ4DACC8AQEAAAABwAFAAAAAAc8BAQAAAAHhAQAAAOEBAuMBAAAA4wEC5QEAAADlAQLmAQEAAAABARYAAI8BACAHvAEBAAAAAcABQAAAAAHPAQEAAAAB4QEAAADhAQLjAQAAAOMBAuUBAAAA5QEC5gEBAAAAAQEWAACRAQAwARYAAJEBADAJBwAAjwMAIAgAAJADACC8AQEA5gIAIcABQADnAgAhzwEBAOYCACHhAQAAjAPhASLjAQAAjQPjASLlAQAAjgPlASLmAQEA5gIAIQIAAAAcACAWAACUAQAgB7wBAQDmAgAhwAFAAOcCACHPAQEA5gIAIeEBAACMA-EBIuMBAACNA-MBIuUBAACOA-UBIuYBAQDmAgAhAgAAABoAIBYAAJYBACACAAAAGgAgFgAAlgEAIAMAAAAcACAdAACPAQAgHgAAlAEAIAEAAAAcACABAAAAGgAgAwQAAIkDACAjAACLAwAgJAAAigMAIAq5AQAArAIAMLoBAACdAQAQuwEAAKwCADC8AQEAkgIAIcABQACTAgAhzwEBAJICACHhAQAArQLhASLjAQAArgLjASLlAQAArwLlASLmAQEAkgIAIQMAAAAaACABAACcAQAwIgAAnQEAIAMAAAAaACABAAAbADACAAAcACABAAAACwAgAQAAAAsAIAMAAAAJACABAAAKADACAAALACADAAAACQAgAQAACgAwAgAACwAgAwAAAAkAIAEAAAoAMAIAAAsAIAcJAACHAwAgCgAAiAMAILwBAQAAAAHaAQEAAAAB3QEBAAAAAd4BCAAAAAHfAQIAAAABARYAAKUBACAFvAEBAAAAAdoBAQAAAAHdAQEAAAAB3gEIAAAAAd8BAgAAAAEBFgAApwEAMAEWAACnAQAwBwkAAIUDACAKAACGAwAgvAEBAOYCACHaAQEA5gIAId0BAQDmAgAh3gEIAIQDACHfAQIA-gIAIQIAAAALACAWAACqAQAgBbwBAQDmAgAh2gEBAOYCACHdAQEA5gIAId4BCACEAwAh3wECAPoCACECAAAACQAgFgAArAEAIAIAAAAJACAWAACsAQAgAwAAAAsAIB0AAKUBACAeAACqAQAgAQAAAAsAIAEAAAAJACAFBAAA_wIAICMAAIIDACAkAACBAwAgNQAAgAMAIDYAAIMDACAIuQEAAKkCADC6AQAAswEAELsBAACpAgAwvAEBAJICACHaAQEAkgIAId0BAQCSAgAh3gEIAKoCACHfAQIApgIAIQMAAAAJACABAACyAQAwIgAAswEAIAMAAAAJACABAAAKADACAAALACABAAAAEQAgAQAAABEAIAMAAAAPACABAAAQADACAAARACADAAAADwAgAQAAEAAwAgAAEQAgAwAAAA8AIAEAABAAMAIAABEAIAgHAAD9AgAgCgAA_gIAILwBAQAAAAHAAUAAAAABzwEBAAAAAdoBAQAAAAHbAQIAAAAB3AEBAAAAAQEWAAC7AQAgBrwBAQAAAAHAAUAAAAABzwEBAAAAAdoBAQAAAAHbAQIAAAAB3AEBAAAAAQEWAAC9AQAwARYAAL0BADAIBwAA-wIAIAoAAPwCACC8AQEA5gIAIcABQADnAgAhzwEBAOYCACHaAQEA5gIAIdsBAgD6AgAh3AEBAOYCACECAAAAEQAgFgAAwAEAIAa8AQEA5gIAIcABQADnAgAhzwEBAOYCACHaAQEA5gIAIdsBAgD6AgAh3AEBAOYCACECAAAADwAgFgAAwgEAIAIAAAAPACAWAADCAQAgAwAAABEAIB0AALsBACAeAADAAQAgAQAAABEAIAEAAAAPACAFBAAA9QIAICMAAPgCACAkAAD3AgAgNQAA9gIAIDYAAPkCACAJuQEAAKUCADC6AQAAyQEAELsBAAClAgAwvAEBAJICACHAAUAAkwIAIc8BAQCSAgAh2gEBAJICACHbAQIApgIAIdwBAQCSAgAhAwAAAA8AIAEAAMgBADAiAADJAQAgAwAAAA8AIAEAABAAMAIAABEAIAEAAAAiACABAAAAIgAgAwAAACAAIAEAACEAMAIAACIAIAMAAAAgACABAAAhADACAAAiACADAAAAIAAgAQAAIQAwAgAAIgAgCQcAAPQCACC8AQEAAAABvwFAAAAAAcABQAAAAAHBAUAAAAABzwEBAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAQEWAADRAQAgCLwBAQAAAAG_AUAAAAABwAFAAAAAAcEBQAAAAAHPAQEAAAAB1wEBAAAAAdgBAQAAAAHZAQEAAAABARYAANMBADABFgAA0wEAMAkHAADzAgAgvAEBAOYCACG_AUAA5wIAIcABQADnAgAhwQFAAOcCACHPAQEA5gIAIdcBAQDmAgAh2AEBAOwCACHZAQEA7AIAIQIAAAAiACAWAADWAQAgCLwBAQDmAgAhvwFAAOcCACHAAUAA5wIAIcEBQADnAgAhzwEBAOYCACHXAQEA5gIAIdgBAQDsAgAh2QEBAOwCACECAAAAIAAgFgAA2AEAIAIAAAAgACAWAADYAQAgAwAAACIAIB0AANEBACAeAADWAQAgAQAAACIAIAEAAAAgACAFBAAA8AIAICMAAPICACAkAADxAgAg2AEAAOgCACDZAQAA6AIAIAu5AQAApAIAMLoBAADfAQAQuwEAAKQCADC8AQEAkgIAIb8BQACTAgAhwAFAAJMCACHBAUAAkwIAIc8BAQCSAgAh1wEBAJICACHYAQEAnQIAIdkBAQCdAgAhAwAAACAAIAEAAN4BADAiAADfAQAgAwAAACAAIAEAACEAMAIAACIAIAEAAAAmACABAAAAJgAgAwAAACQAIAEAACUAMAIAACYAIAMAAAAkACABAAAlADACAAAmACADAAAAJAAgAQAAJQAwAgAAJgAgDgcAAO8CACC8AQEAAAABwAFAAAAAAcEBQAAAAAHNAQEAAAABzgEBAAAAAc8BAQAAAAHQAQEAAAAB0QEBAAAAAdIBAQAAAAHTAUAAAAAB1AFAAAAAAdUBAQAAAAHWAQEAAAABARYAAOcBACANvAEBAAAAAcABQAAAAAHBAUAAAAABzQEBAAAAAc4BAQAAAAHPAQEAAAAB0AEBAAAAAdEBAQAAAAHSAQEAAAAB0wFAAAAAAdQBQAAAAAHVAQEAAAAB1gEBAAAAAQEWAADpAQAwARYAAOkBADAOBwAA7gIAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIc0BAQDmAgAhzgEBAOYCACHPAQEA5gIAIdABAQDsAgAh0QEBAOwCACHSAQEA7AIAIdMBQADtAgAh1AFAAO0CACHVAQEA7AIAIdYBAQDsAgAhAgAAACYAIBYAAOwBACANvAEBAOYCACHAAUAA5wIAIcEBQADnAgAhzQEBAOYCACHOAQEA5gIAIc8BAQDmAgAh0AEBAOwCACHRAQEA7AIAIdIBAQDsAgAh0wFAAO0CACHUAUAA7QIAIdUBAQDsAgAh1gEBAOwCACECAAAAJAAgFgAA7gEAIAIAAAAkACAWAADuAQAgAwAAACYAIB0AAOcBACAeAADsAQAgAQAAACYAIAEAAAAkACAKBAAA6QIAICMAAOsCACAkAADqAgAg0AEAAOgCACDRAQAA6AIAINIBAADoAgAg0wEAAOgCACDUAQAA6AIAINUBAADoAgAg1gEAAOgCACAQuQEAAJwCADC6AQAA9QEAELsBAACcAgAwvAEBAJICACHAAUAAkwIAIcEBQACTAgAhzQEBAJICACHOAQEAkgIAIc8BAQCSAgAh0AEBAJ0CACHRAQEAnQIAIdIBAQCdAgAh0wFAAJ4CACHUAUAAngIAIdUBAQCdAgAh1gEBAJ0CACEDAAAAJAAgAQAA9AEAMCIAAPUBACADAAAAJAAgAQAAJQAwAgAAJgAgCbkBAACZAgAwugEAAPsBABC7AQAAmQIAMLwBAQAAAAG9AQEAmgIAIb4BAQCaAgAhvwFAAJsCACHAAUAAmwIAIcEBQACbAgAhAQAAAPgBACABAAAA-AEAIAm5AQAAmQIAMLoBAAD7AQAQuwEAAJkCADC8AQEAmgIAIb0BAQCaAgAhvgEBAJoCACG_AUAAmwIAIcABQACbAgAhwQFAAJsCACEAAwAAAPsBACABAAD8AQAwAgAA-AEAIAMAAAD7AQAgAQAA_AEAMAIAAPgBACADAAAA-wEAIAEAAPwBADACAAD4AQAgBrwBAQAAAAG9AQEAAAABvgEBAAAAAb8BQAAAAAHAAUAAAAABwQFAAAAAAQEWAACAAgAgBrwBAQAAAAG9AQEAAAABvgEBAAAAAb8BQAAAAAHAAUAAAAABwQFAAAAAAQEWAACCAgAwARYAAIICADAGvAEBAOYCACG9AQEA5gIAIb4BAQDmAgAhvwFAAOcCACHAAUAA5wIAIcEBQADnAgAhAgAAAPgBACAWAACFAgAgBrwBAQDmAgAhvQEBAOYCACG-AQEA5gIAIb8BQADnAgAhwAFAAOcCACHBAUAA5wIAIQIAAAD7AQAgFgAAhwIAIAIAAAD7AQAgFgAAhwIAIAMAAAD4AQAgHQAAgAIAIB4AAIUCACABAAAA-AEAIAEAAAD7AQAgAwQAAOMCACAjAADlAgAgJAAA5AIAIAm5AQAAkQIAMLoBAACOAgAQuwEAAJECADC8AQEAkgIAIb0BAQCSAgAhvgEBAJICACG_AUAAkwIAIcABQACTAgAhwQFAAJMCACEDAAAA-wEAIAEAAI0CADAiAACOAgAgAwAAAPsBACABAAD8AQAwAgAA-AEAIAm5AQAAkQIAMLoBAACOAgAQuwEAAJECADC8AQEAkgIAIb0BAQCSAgAhvgEBAJICACG_AUAAkwIAIcABQACTAgAhwQFAAJMCACEOBAAAlQIAICMAAJgCACAkAACYAgAgwgEBAAAAAcMBAQAAAATEAQEAAAAExQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQCXAgAhygEBAAAAAcsBAQAAAAHMAQEAAAABCwQAAJUCACAjAACWAgAgJAAAlgIAIMIBQAAAAAHDAUAAAAAExAFAAAAABMUBQAAAAAHGAUAAAAABxwFAAAAAAcgBQAAAAAHJAUAAlAIAIQsEAACVAgAgIwAAlgIAICQAAJYCACDCAUAAAAABwwFAAAAABMQBQAAAAATFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAJQCACEIwgECAAAAAcMBAgAAAATEAQIAAAAExQECAAAAAcYBAgAAAAHHAQIAAAAByAECAAAAAckBAgCVAgAhCMIBQAAAAAHDAUAAAAAExAFAAAAABMUBQAAAAAHGAUAAAAABxwFAAAAAAcgBQAAAAAHJAUAAlgIAIQ4EAACVAgAgIwAAmAIAICQAAJgCACDCAQEAAAABwwEBAAAABMQBAQAAAATFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAJcCACHKAQEAAAABywEBAAAAAcwBAQAAAAELwgEBAAAAAcMBAQAAAATEAQEAAAAExQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQCYAgAhygEBAAAAAcsBAQAAAAHMAQEAAAABCbkBAACZAgAwugEAAPsBABC7AQAAmQIAMLwBAQCaAgAhvQEBAJoCACG-AQEAmgIAIb8BQACbAgAhwAFAAJsCACHBAUAAmwIAIQvCAQEAAAABwwEBAAAABMQBAQAAAATFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAJgCACHKAQEAAAABywEBAAAAAcwBAQAAAAEIwgFAAAAAAcMBQAAAAATEAUAAAAAExQFAAAAAAcYBQAAAAAHHAUAAAAAByAFAAAAAAckBQACWAgAhELkBAACcAgAwugEAAPUBABC7AQAAnAIAMLwBAQCSAgAhwAFAAJMCACHBAUAAkwIAIc0BAQCSAgAhzgEBAJICACHPAQEAkgIAIdABAQCdAgAh0QEBAJ0CACHSAQEAnQIAIdMBQACeAgAh1AFAAJ4CACHVAQEAnQIAIdYBAQCdAgAhDgQAAKACACAjAACjAgAgJAAAowIAIMIBAQAAAAHDAQEAAAAFxAEBAAAABcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAogIAIcoBAQAAAAHLAQEAAAABzAEBAAAAAQsEAACgAgAgIwAAoQIAICQAAKECACDCAUAAAAABwwFAAAAABcQBQAAAAAXFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAJ8CACELBAAAoAIAICMAAKECACAkAAChAgAgwgFAAAAAAcMBQAAAAAXEAUAAAAAFxQFAAAAAAcYBQAAAAAHHAUAAAAAByAFAAAAAAckBQACfAgAhCMIBAgAAAAHDAQIAAAAFxAECAAAABcUBAgAAAAHGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIAoAIAIQjCAUAAAAABwwFAAAAABcQBQAAAAAXFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAKECACEOBAAAoAIAICMAAKMCACAkAACjAgAgwgEBAAAAAcMBAQAAAAXEAQEAAAAFxQEBAAAAAcYBAQAAAAHHAQEAAAAByAEBAAAAAckBAQCiAgAhygEBAAAAAcsBAQAAAAHMAQEAAAABC8IBAQAAAAHDAQEAAAAFxAEBAAAABcUBAQAAAAHGAQEAAAABxwEBAAAAAcgBAQAAAAHJAQEAowIAIcoBAQAAAAHLAQEAAAABzAEBAAAAAQu5AQAApAIAMLoBAADfAQAQuwEAAKQCADC8AQEAkgIAIb8BQACTAgAhwAFAAJMCACHBAUAAkwIAIc8BAQCSAgAh1wEBAJICACHYAQEAnQIAIdkBAQCdAgAhCbkBAAClAgAwugEAAMkBABC7AQAApQIAMLwBAQCSAgAhwAFAAJMCACHPAQEAkgIAIdoBAQCSAgAh2wECAKYCACHcAQEAkgIAIQ0EAACVAgAgIwAAlQIAICQAAJUCACA1AACoAgAgNgAAlQIAIMIBAgAAAAHDAQIAAAAExAECAAAABMUBAgAAAAHGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIApwIAIQ0EAACVAgAgIwAAlQIAICQAAJUCACA1AACoAgAgNgAAlQIAIMIBAgAAAAHDAQIAAAAExAECAAAABMUBAgAAAAHGAQIAAAABxwECAAAAAcgBAgAAAAHJAQIApwIAIQjCAQgAAAABwwEIAAAABMQBCAAAAATFAQgAAAABxgEIAAAAAccBCAAAAAHIAQgAAAAByQEIAKgCACEIuQEAAKkCADC6AQAAswEAELsBAACpAgAwvAEBAJICACHaAQEAkgIAId0BAQCSAgAh3gEIAKoCACHfAQIApgIAIQ0EAACVAgAgIwAAqAIAICQAAKgCACA1AACoAgAgNgAAqAIAIMIBCAAAAAHDAQgAAAAExAEIAAAABMUBCAAAAAHGAQgAAAABxwEIAAAAAcgBCAAAAAHJAQgAqwIAIQ0EAACVAgAgIwAAqAIAICQAAKgCACA1AACoAgAgNgAAqAIAIMIBCAAAAAHDAQgAAAAExAEIAAAABMUBCAAAAAHGAQgAAAABxwEIAAAAAcgBCAAAAAHJAQgAqwIAIQq5AQAArAIAMLoBAACdAQAQuwEAAKwCADC8AQEAkgIAIcABQACTAgAhzwEBAJICACHhAQAArQLhASLjAQAArgLjASLlAQAArwLlASLmAQEAkgIAIQcEAACVAgAgIwAAtQIAICQAALUCACDCAQAAAOEBAsMBAAAA4QEIxAEAAADhAQjJAQAAtALhASIHBAAAlQIAICMAALMCACAkAACzAgAgwgEAAADjAQLDAQAAAOMBCMQBAAAA4wEIyQEAALIC4wEiBwQAAJUCACAjAACxAgAgJAAAsQIAIMIBAAAA5QECwwEAAADlAQjEAQAAAOUBCMkBAACwAuUBIgcEAACVAgAgIwAAsQIAICQAALECACDCAQAAAOUBAsMBAAAA5QEIxAEAAADlAQjJAQAAsALlASIEwgEAAADlAQLDAQAAAOUBCMQBAAAA5QEIyQEAALEC5QEiBwQAAJUCACAjAACzAgAgJAAAswIAIMIBAAAA4wECwwEAAADjAQjEAQAAAOMBCMkBAACyAuMBIgTCAQAAAOMBAsMBAAAA4wEIxAEAAADjAQjJAQAAswLjASIHBAAAlQIAICMAALUCACAkAAC1AgAgwgEAAADhAQLDAQAAAOEBCMQBAAAA4QEIyQEAALQC4QEiBMIBAAAA4QECwwEAAADhAQjEAQAAAOEBCMkBAAC1AuEBIge5AQAAtgIAMLoBAACHAQAQuwEAALYCADC8AQEAkgIAIc8BAQCSAgAh2gEBAJICACHfAQIApgIAIQa5AQAAtwIAMLoBAABxABC7AQAAtwIAMLwBAQCSAgAhwAFAAJMCACHnAQEAkgIAIQcDAAC5AgAguQEAALgCADC6AQAAXgAQuwEAALgCADC8AQEAmgIAIcABQACbAgAh5wEBAJoCACED6AEAAAMAIOkBAAADACDqAQAAAwAgDLkBAAC6AgAwugEAAFgAELsBAAC6AgAwvAEBAJICACHAAUAAkwIAId4BCACqAgAh5wEBAJICACHrAQIApgIAIewBAQCSAgAh7QEBAJ0CACHuAQEAkgIAIe8BAQCSAgAhDLkBAAC7AgAwugEAAEIAELsBAAC7AgAwvAEBAJICACHAAUAAkwIAIcEBQACTAgAh4QEAAL0C9AEi5wEBAJICACHtAQEAnQIAIfABAQCSAgAh8gEAALwC8gEi9AEgAL4CACEHBAAAlQIAICMAAMQCACAkAADEAgAgwgEAAADyAQLDAQAAAPIBCMQBAAAA8gEIyQEAAMMC8gEiBwQAAJUCACAjAADCAgAgJAAAwgIAIMIBAAAA9AECwwEAAAD0AQjEAQAAAPQBCMkBAADBAvQBIgUEAACVAgAgIwAAwAIAICQAAMACACDCASAAAAAByQEgAL8CACEFBAAAlQIAICMAAMACACAkAADAAgAgwgEgAAAAAckBIAC_AgAhAsIBIAAAAAHJASAAwAIAIQcEAACVAgAgIwAAwgIAICQAAMICACDCAQAAAPQBAsMBAAAA9AEIxAEAAAD0AQjJAQAAwQL0ASIEwgEAAAD0AQLDAQAAAPQBCMQBAAAA9AEIyQEAAMIC9AEiBwQAAJUCACAjAADEAgAgJAAAxAIAIMIBAAAA8gECwwEAAADyAQjEAQAAAPIBCMkBAADDAvIBIgTCAQAAAPIBAsMBAAAA8gEIxAEAAADyAQjJAQAAxALyASISAwAAuQIAIAsAAMsCACANAADKAgAgDgAAzAIAIA8AAM0CACAQAADOAgAguQEAAMUCADC6AQAALwAQuwEAAMUCADC8AQEAmgIAIcABQACbAgAhwQFAAJsCACHhAQAAxwL0ASLnAQEAmgIAIe0BAQDJAgAh8AEBAJoCACHyAQAAxgLyASL0ASAAyAIAIQTCAQAAAPIBAsMBAAAA8gEIxAEAAADyAQjJAQAAxALyASIEwgEAAAD0AQLDAQAAAPQBCMQBAAAA9AEIyQEAAMIC9AEiAsIBIAAAAAHJASAAwAIAIQvCAQEAAAABwwEBAAAABcQBAQAAAAXFAQEAAAABxgEBAAAAAccBAQAAAAHIAQEAAAAByQEBAKMCACHKAQEAAAABywEBAAAAAcwBAQAAAAED6AEAABoAIOkBAAAaACDqAQAAGgAgA-gBAAAPACDpAQAADwAg6gEAAA8AIAPoAQAAEwAg6QEAABMAIOoBAAATACAD6AEAACAAIOkBAAAgACDqAQAAIAAgA-gBAAAkACDpAQAAJAAg6gEAACQAIBEHAADRAgAguQEAAM8CADC6AQAAJAAQuwEAAM8CADC8AQEAmgIAIcABQACbAgAhwQFAAJsCACHNAQEAmgIAIc4BAQCaAgAhzwEBAJoCACHQAQEAyQIAIdEBAQDJAgAh0gEBAMkCACHTAUAA0AIAIdQBQADQAgAh1QEBAMkCACHWAQEAyQIAIQjCAUAAAAABwwFAAAAABcQBQAAAAAXFAUAAAAABxgFAAAAAAccBQAAAAAHIAUAAAAAByQFAAKECACEUAwAAuQIAIAsAAMsCACANAADKAgAgDgAAzAIAIA8AAM0CACAQAADOAgAguQEAAMUCADC6AQAALwAQuwEAAMUCADC8AQEAmgIAIcABQACbAgAhwQFAAJsCACHhAQAAxwL0ASLnAQEAmgIAIe0BAQDJAgAh8AEBAJoCACHyAQAAxgLyASL0ASAAyAIAIfYBAAAvACD3AQAALwAgDAcAANECACC5AQAA0gIAMLoBAAAgABC7AQAA0gIAMLwBAQCaAgAhvwFAAJsCACHAAUAAmwIAIcEBQACbAgAhzwEBAJoCACHXAQEAmgIAIdgBAQDJAgAh2QEBAMkCACEMBwAA0QIAIAgAANcCACC5AQAA0wIAMLoBAAAaABC7AQAA0wIAMLwBAQCaAgAhwAFAAJsCACHPAQEAmgIAIeEBAADUAuEBIuMBAADVAuMBIuUBAADWAuUBIuYBAQCaAgAhBMIBAAAA4QECwwEAAADhAQjEAQAAAOEBCMkBAAC1AuEBIgTCAQAAAOMBAsMBAAAA4wEIxAEAAADjAQjJAQAAswLjASIEwgEAAADlAQLDAQAAAOUBCMQBAAAA5QEIyQEAALEC5QEiA-gBAAAJACDpAQAACQAg6gEAAAkAIALPAQEAAAAB2gEBAAAAAQkHAADRAgAgCgAA2wIAILkBAADZAgAwugEAABMAELsBAADZAgAwvAEBAJoCACHPAQEAmgIAIdoBAQCaAgAh3wECANoCACEIwgECAAAAAcMBAgAAAATEAQIAAAAExQECAAAAAcYBAgAAAAHHAQIAAAAByAECAAAAAckBAgCVAgAhEwUAAOICACAGAADRAgAgCAAA1wIAIAsAAMsCACAMAADMAgAguQEAAOECADC6AQAAAwAQuwEAAOECADC8AQEAmgIAIcABQACbAgAh3gEIAN8CACHnAQEAmgIAIesBAgDaAgAh7AEBAJoCACHtAQEAyQIAIe4BAQCaAgAh7wEBAJoCACH2AQAAAwAg9wEAAAMAIALPAQEAAAAB2gEBAAAAAQsHAADRAgAgCgAA2wIAILkBAADdAgAwugEAAA8AELsBAADdAgAwvAEBAJoCACHAAUAAmwIAIc8BAQCaAgAh2gEBAJoCACHbAQIA2gIAIdwBAQCaAgAhCgkAAOACACAKAADbAgAguQEAAN4CADC6AQAACQAQuwEAAN4CADC8AQEAmgIAIdoBAQCaAgAh3QEBAJoCACHeAQgA3wIAId8BAgDaAgAhCMIBCAAAAAHDAQgAAAAExAEIAAAABMUBCAAAAAHGAQgAAAABxwEIAAAAAcgBCAAAAAHJAQgAqAIAIQ4HAADRAgAgCAAA1wIAILkBAADTAgAwugEAABoAELsBAADTAgAwvAEBAJoCACHAAUAAmwIAIc8BAQCaAgAh4QEAANQC4QEi4wEAANUC4wEi5QEAANYC5QEi5gEBAJoCACH2AQAAGgAg9wEAABoAIBEFAADiAgAgBgAA0QIAIAgAANcCACALAADLAgAgDAAAzAIAILkBAADhAgAwugEAAAMAELsBAADhAgAwvAEBAJoCACHAAUAAmwIAId4BCADfAgAh5wEBAJoCACHrAQIA2gIAIewBAQCaAgAh7QEBAMkCACHuAQEAmgIAIe8BAQCaAgAhCQMAALkCACC5AQAAuAIAMLoBAABeABC7AQAAuAIAMLwBAQCaAgAhwAFAAJsCACHnAQEAmgIAIfYBAABeACD3AQAAXgAgAAAAAfsBAQAAAAEB-wFAAAAAAQAAAAAB-wEBAAAAAQH7AUAAAAABBR0AAIIFACAeAACFBQAg-AEAAIMFACD5AQAAhAUAIP4BAAABACADHQAAggUAIPgBAACDBQAg_gEAAAEAIAAAAAUdAAD9BAAgHgAAgAUAIPgBAAD-BAAg-QEAAP8EACD-AQAAAQAgAx0AAP0EACD4AQAA_gQAIP4BAAABACAAAAAAAAX7AQIAAAABgQICAAAAAYICAgAAAAGDAgIAAAABhAICAAAAAQUdAAD1BAAgHgAA-wQAIPgBAAD2BAAg-QEAAPoEACD-AQAAAQAgBR0AAPMEACAeAAD4BAAg-AEAAPQEACD5AQAA9wQAIP4BAAAFACADHQAA9QQAIPgBAAD2BAAg_gEAAAEAIAMdAADzBAAg-AEAAPQEACD-AQAABQAgAAAAAAAF-wEIAAAAAYECCAAAAAGCAggAAAABgwIIAAAAAYQCCAAAAAEFHQAA6wQAIB4AAPEEACD4AQAA7AQAIPkBAADwBAAg_gEAABwAIAUdAADpBAAgHgAA7gQAIPgBAADqBAAg-QEAAO0EACD-AQAABQAgAx0AAOsEACD4AQAA7AQAIP4BAAAcACADHQAA6QQAIPgBAADqBAAg_gEAAAUAIAAAAAH7AQAAAOEBAgH7AQAAAOMBAgH7AQAAAOUBAgUdAADjBAAgHgAA5wQAIPgBAADkBAAg-QEAAOYEACD-AQAAAQAgCx0AAJEDADAeAACWAwAw-AEAAJIDADD5AQAAkwMAMPoBAACUAwAg-wEAAJUDADD8AQAAlQMAMP0BAACVAwAw_gEAAJUDADD_AQAAlwMAMIACAACYAwAwBQoAAIgDACC8AQEAAAAB2gEBAAAAAd4BCAAAAAHfAQIAAAABAgAAAAsAIB0AAJwDACADAAAACwAgHQAAnAMAIB4AAJsDACABFgAA5QQAMAoJAADgAgAgCgAA2wIAILkBAADeAgAwugEAAAkAELsBAADeAgAwvAEBAAAAAdoBAQCaAgAh3QEBAJoCACHeAQgA3wIAId8BAgDaAgAhAgAAAAsAIBYAAJsDACACAAAAmQMAIBYAAJoDACAIuQEAAJgDADC6AQAAmQMAELsBAACYAwAwvAEBAJoCACHaAQEAmgIAId0BAQCaAgAh3gEIAN8CACHfAQIA2gIAIQi5AQAAmAMAMLoBAACZAwAQuwEAAJgDADC8AQEAmgIAIdoBAQCaAgAh3QEBAJoCACHeAQgA3wIAId8BAgDaAgAhBLwBAQDmAgAh2gEBAOYCACHeAQgAhAMAId8BAgD6AgAhBQoAAIYDACC8AQEA5gIAIdoBAQDmAgAh3gEIAIQDACHfAQIA-gIAIQUKAACIAwAgvAEBAAAAAdoBAQAAAAHeAQgAAAAB3wECAAAAAQMdAADjBAAg-AEAAOQEACD-AQAAAQAgBB0AAJEDADD4AQAAkgMAMPoBAACUAwAg_gEAAJUDADAAAAAAAAUdAADbBAAgHgAA4QQAIPgBAADcBAAg-QEAAOAEACD-AQAAAQAgBR0AANkEACAeAADeBAAg-AEAANoEACD5AQAA3QQAIP4BAAAFACADHQAA2wQAIPgBAADcBAAg_gEAAAEAIAMdAADZBAAg-AEAANoEACD-AQAABQAgAAAACx0AAKwDADAeAACxAwAw-AEAAK0DADD5AQAArgMAMPoBAACvAwAg-wEAALADADD8AQAAsAMAMP0BAACwAwAw_gEAALADADD_AQAAsgMAMIACAACzAwAwDAYAAN0DACAIAADeAwAgCwAA3wMAIAwAAOADACC8AQEAAAABwAFAAAAAAd4BCAAAAAHnAQEAAAAB6wECAAAAAewBAQAAAAHtAQEAAAAB7wEBAAAAAQIAAAAFACAdAADcAwAgAwAAAAUAIB0AANwDACAeAAC2AwAgARYAANgEADARBQAA4gIAIAYAANECACAIAADXAgAgCwAAywIAIAwAAMwCACC5AQAA4QIAMLoBAAADABC7AQAA4QIAMLwBAQAAAAHAAUAAmwIAId4BCADfAgAh5wEBAJoCACHrAQIA2gIAIewBAQCaAgAh7QEBAMkCACHuAQEAmgIAIe8BAQCaAgAhAgAAAAUAIBYAALYDACACAAAAtAMAIBYAALUDACAMuQEAALMDADC6AQAAtAMAELsBAACzAwAwvAEBAJoCACHAAUAAmwIAId4BCADfAgAh5wEBAJoCACHrAQIA2gIAIewBAQCaAgAh7QEBAMkCACHuAQEAmgIAIe8BAQCaAgAhDLkBAACzAwAwugEAALQDABC7AQAAswMAMLwBAQCaAgAhwAFAAJsCACHeAQgA3wIAIecBAQCaAgAh6wECANoCACHsAQEAmgIAIe0BAQDJAgAh7gEBAJoCACHvAQEAmgIAIQi8AQEA5gIAIcABQADnAgAh3gEIAIQDACHnAQEA5gIAIesBAgD6AgAh7AEBAOYCACHtAQEA7AIAIe8BAQDmAgAhDAYAALcDACAIAAC4AwAgCwAAuQMAIAwAALoDACC8AQEA5gIAIcABQADnAgAh3gEIAIQDACHnAQEA5gIAIesBAgD6AgAh7AEBAOYCACHtAQEA7AIAIe8BAQDmAgAhBR0AANAEACAeAADWBAAg-AEAANEEACD5AQAA1QQAIP4BAAABACALHQAA0wMAMB4AANcDADD4AQAA1AMAMPkBAADVAwAw-gEAANYDACD7AQAAlQMAMPwBAACVAwAw_QEAAJUDADD-AQAAlQMAMP8BAADYAwAwgAIAAJgDADALHQAAxwMAMB4AAMwDADD4AQAAyAMAMPkBAADJAwAw-gEAAMoDACD7AQAAywMAMPwBAADLAwAw_QEAAMsDADD-AQAAywMAMP8BAADNAwAwgAIAAM4DADALHQAAuwMAMB4AAMADADD4AQAAvAMAMPkBAAC9AwAw-gEAAL4DACD7AQAAvwMAMPwBAAC_AwAw_QEAAL8DADD-AQAAvwMAMP8BAADBAwAwgAIAAMIDADAEBwAApgMAILwBAQAAAAHPAQEAAAAB3wECAAAAAQIAAAAVACAdAADGAwAgAwAAABUAIB0AAMYDACAeAADFAwAgARYAANQEADAKBwAA0QIAIAoAANsCACC5AQAA2QIAMLoBAAATABC7AQAA2QIAMLwBAQAAAAHPAQEAmgIAIdoBAQCaAgAh3wECANoCACH1AQAA2AIAIAIAAAAVACAWAADFAwAgAgAAAMMDACAWAADEAwAgB7kBAADCAwAwugEAAMMDABC7AQAAwgMAMLwBAQCaAgAhzwEBAJoCACHaAQEAmgIAId8BAgDaAgAhB7kBAADCAwAwugEAAMMDABC7AQAAwgMAMLwBAQCaAgAhzwEBAJoCACHaAQEAmgIAId8BAgDaAgAhA7wBAQDmAgAhzwEBAOYCACHfAQIA-gIAIQQHAACkAwAgvAEBAOYCACHPAQEA5gIAId8BAgD6AgAhBAcAAKYDACC8AQEAAAABzwEBAAAAAd8BAgAAAAEGBwAA_QIAILwBAQAAAAHAAUAAAAABzwEBAAAAAdsBAgAAAAHcAQEAAAABAgAAABEAIB0AANIDACADAAAAEQAgHQAA0gMAIB4AANEDACABFgAA0wQAMAwHAADRAgAgCgAA2wIAILkBAADdAgAwugEAAA8AELsBAADdAgAwvAEBAAAAAcABQACbAgAhzwEBAJoCACHaAQEAmgIAIdsBAgDaAgAh3AEBAJoCACH1AQAA3AIAIAIAAAARACAWAADRAwAgAgAAAM8DACAWAADQAwAgCbkBAADOAwAwugEAAM8DABC7AQAAzgMAMLwBAQCaAgAhwAFAAJsCACHPAQEAmgIAIdoBAQCaAgAh2wECANoCACHcAQEAmgIAIQm5AQAAzgMAMLoBAADPAwAQuwEAAM4DADC8AQEAmgIAIcABQACbAgAhzwEBAJoCACHaAQEAmgIAIdsBAgDaAgAh3AEBAJoCACEFvAEBAOYCACHAAUAA5wIAIc8BAQDmAgAh2wECAPoCACHcAQEA5gIAIQYHAAD7AgAgvAEBAOYCACHAAUAA5wIAIc8BAQDmAgAh2wECAPoCACHcAQEA5gIAIQYHAAD9AgAgvAEBAAAAAcABQAAAAAHPAQEAAAAB2wECAAAAAdwBAQAAAAEFCQAAhwMAILwBAQAAAAHdAQEAAAAB3gEIAAAAAd8BAgAAAAECAAAACwAgHQAA2wMAIAMAAAALACAdAADbAwAgHgAA2gMAIAEWAADSBAAwAgAAAAsAIBYAANoDACACAAAAmQMAIBYAANkDACAEvAEBAOYCACHdAQEA5gIAId4BCACEAwAh3wECAPoCACEFCQAAhQMAILwBAQDmAgAh3QEBAOYCACHeAQgAhAMAId8BAgD6AgAhBQkAAIcDACC8AQEAAAAB3QEBAAAAAd4BCAAAAAHfAQIAAAABDAYAAN0DACAIAADeAwAgCwAA3wMAIAwAAOADACC8AQEAAAABwAFAAAAAAd4BCAAAAAHnAQEAAAAB6wECAAAAAewBAQAAAAHtAQEAAAAB7wEBAAAAAQMdAADQBAAg-AEAANEEACD-AQAAAQAgBB0AANMDADD4AQAA1AMAMPoBAADWAwAg_gEAAJUDADAEHQAAxwMAMPgBAADIAwAw-gEAAMoDACD-AQAAywMAMAQdAAC7AwAw-AEAALwDADD6AQAAvgMAIP4BAAC_AwAwBB0AAKwDADD4AQAArQMAMPoBAACvAwAg_gEAALADADAAAAAAAAAFHQAAywQAIB4AAM4EACD4AQAAzAQAIPkBAADNBAAg_gEAAFsAIAMdAADLBAAg-AEAAMwEACD-AQAAWwAgAAAAAfsBAAAA8gECAfsBAAAA9AECAfsBIAAAAAELHQAArAQAMB4AALAEADD4AQAArQQAMPkBAACuBAAw-gEAAK8EACD7AQAAsAMAMPwBAACwAwAw_QEAALADADD-AQAAsAMAMP8BAACxBAAwgAIAALMDADALHQAAoAQAMB4AAKUEADD4AQAAoQQAMPkBAACiBAAw-gEAAKMEACD7AQAApAQAMPwBAACkBAAw_QEAAKQEADD-AQAApAQAMP8BAACmBAAwgAIAAKcEADALHQAAlwQAMB4AAJsEADD4AQAAmAQAMPkBAACZBAAw-gEAAJoEACD7AQAAywMAMPwBAADLAwAw_QEAAMsDADD-AQAAywMAMP8BAACcBAAwgAIAAM4DADALHQAAjgQAMB4AAJIEADD4AQAAjwQAMPkBAACQBAAw-gEAAJEEACD7AQAAvwMAMPwBAAC_AwAw_QEAAL8DADD-AQAAvwMAMP8BAACTBAAwgAIAAMIDADALHQAAggQAMB4AAIcEADD4AQAAgwQAMPkBAACEBAAw-gEAAIUEACD7AQAAhgQAMPwBAACGBAAw_QEAAIYEADD-AQAAhgQAMP8BAACIBAAwgAIAAIkEADALHQAA9gMAMB4AAPsDADD4AQAA9wMAMPkBAAD4AwAw-gEAAPkDACD7AQAA-gMAMPwBAAD6AwAw_QEAAPoDADD-AQAA-gMAMP8BAAD8AwAwgAIAAP0DADAMvAEBAAAAAcABQAAAAAHBAUAAAAABzQEBAAAAAc4BAQAAAAHQAQEAAAAB0QEBAAAAAdIBAQAAAAHTAUAAAAAB1AFAAAAAAdUBAQAAAAHWAQEAAAABAgAAACYAIB0AAIEEACADAAAAJgAgHQAAgQQAIB4AAIAEACABFgAAygQAMBEHAADRAgAguQEAAM8CADC6AQAAJAAQuwEAAM8CADC8AQEAAAABwAFAAJsCACHBAUAAmwIAIc0BAQCaAgAhzgEBAJoCACHPAQEAmgIAIdABAQDJAgAh0QEBAMkCACHSAQEAyQIAIdMBQADQAgAh1AFAANACACHVAQEAyQIAIdYBAQDJAgAhAgAAACYAIBYAAIAEACACAAAA_gMAIBYAAP8DACAQuQEAAP0DADC6AQAA_gMAELsBAAD9AwAwvAEBAJoCACHAAUAAmwIAIcEBQACbAgAhzQEBAJoCACHOAQEAmgIAIc8BAQCaAgAh0AEBAMkCACHRAQEAyQIAIdIBAQDJAgAh0wFAANACACHUAUAA0AIAIdUBAQDJAgAh1gEBAMkCACEQuQEAAP0DADC6AQAA_gMAELsBAAD9AwAwvAEBAJoCACHAAUAAmwIAIcEBQACbAgAhzQEBAJoCACHOAQEAmgIAIc8BAQCaAgAh0AEBAMkCACHRAQEAyQIAIdIBAQDJAgAh0wFAANACACHUAUAA0AIAIdUBAQDJAgAh1gEBAMkCACEMvAEBAOYCACHAAUAA5wIAIcEBQADnAgAhzQEBAOYCACHOAQEA5gIAIdABAQDsAgAh0QEBAOwCACHSAQEA7AIAIdMBQADtAgAh1AFAAO0CACHVAQEA7AIAIdYBAQDsAgAhDLwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIc0BAQDmAgAhzgEBAOYCACHQAQEA7AIAIdEBAQDsAgAh0gEBAOwCACHTAUAA7QIAIdQBQADtAgAh1QEBAOwCACHWAQEA7AIAIQy8AQEAAAABwAFAAAAAAcEBQAAAAAHNAQEAAAABzgEBAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAdMBQAAAAAHUAUAAAAAB1QEBAAAAAdYBAQAAAAEHvAEBAAAAAb8BQAAAAAHAAUAAAAABwQFAAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAQIAAAAiACAdAACNBAAgAwAAACIAIB0AAI0EACAeAACMBAAgARYAAMkEADAMBwAA0QIAILkBAADSAgAwugEAACAAELsBAADSAgAwvAEBAAAAAb8BQACbAgAhwAFAAJsCACHBAUAAmwIAIc8BAQCaAgAh1wEBAAAAAdgBAQDJAgAh2QEBAMkCACECAAAAIgAgFgAAjAQAIAIAAACKBAAgFgAAiwQAIAu5AQAAiQQAMLoBAACKBAAQuwEAAIkEADC8AQEAmgIAIb8BQACbAgAhwAFAAJsCACHBAUAAmwIAIc8BAQCaAgAh1wEBAJoCACHYAQEAyQIAIdkBAQDJAgAhC7kBAACJBAAwugEAAIoEABC7AQAAiQQAMLwBAQCaAgAhvwFAAJsCACHAAUAAmwIAIcEBQACbAgAhzwEBAJoCACHXAQEAmgIAIdgBAQDJAgAh2QEBAMkCACEHvAEBAOYCACG_AUAA5wIAIcABQADnAgAhwQFAAOcCACHXAQEA5gIAIdgBAQDsAgAh2QEBAOwCACEHvAEBAOYCACG_AUAA5wIAIcABQADnAgAhwQFAAOcCACHXAQEA5gIAIdgBAQDsAgAh2QEBAOwCACEHvAEBAAAAAb8BQAAAAAHAAUAAAAABwQFAAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAQQKAACnAwAgvAEBAAAAAdoBAQAAAAHfAQIAAAABAgAAABUAIB0AAJYEACADAAAAFQAgHQAAlgQAIB4AAJUEACABFgAAyAQAMAIAAAAVACAWAACVBAAgAgAAAMMDACAWAACUBAAgA7wBAQDmAgAh2gEBAOYCACHfAQIA-gIAIQQKAAClAwAgvAEBAOYCACHaAQEA5gIAId8BAgD6AgAhBAoAAKcDACC8AQEAAAAB2gEBAAAAAd8BAgAAAAEGCgAA_gIAILwBAQAAAAHAAUAAAAAB2gEBAAAAAdsBAgAAAAHcAQEAAAABAgAAABEAIB0AAJ8EACADAAAAEQAgHQAAnwQAIB4AAJ4EACABFgAAxwQAMAIAAAARACAWAACeBAAgAgAAAM8DACAWAACdBAAgBbwBAQDmAgAhwAFAAOcCACHaAQEA5gIAIdsBAgD6AgAh3AEBAOYCACEGCgAA_AIAILwBAQDmAgAhwAFAAOcCACHaAQEA5gIAIdsBAgD6AgAh3AEBAOYCACEGCgAA_gIAILwBAQAAAAHAAUAAAAAB2gEBAAAAAdsBAgAAAAHcAQEAAAABBwgAAJ4DACC8AQEAAAABwAFAAAAAAeEBAAAA4QEC4wEAAADjAQLlAQAAAOUBAuYBAQAAAAECAAAAHAAgHQAAqwQAIAMAAAAcACAdAACrBAAgHgAAqgQAIAEWAADGBAAwDAcAANECACAIAADXAgAguQEAANMCADC6AQAAGgAQuwEAANMCADC8AQEAAAABwAFAAJsCACHPAQEAmgIAIeEBAADUAuEBIuMBAADVAuMBIuUBAADWAuUBIuYBAQCaAgAhAgAAABwAIBYAAKoEACACAAAAqAQAIBYAAKkEACAKuQEAAKcEADC6AQAAqAQAELsBAACnBAAwvAEBAJoCACHAAUAAmwIAIc8BAQCaAgAh4QEAANQC4QEi4wEAANUC4wEi5QEAANYC5QEi5gEBAJoCACEKuQEAAKcEADC6AQAAqAQAELsBAACnBAAwvAEBAJoCACHAAUAAmwIAIc8BAQCaAgAh4QEAANQC4QEi4wEAANUC4wEi5QEAANYC5QEi5gEBAJoCACEGvAEBAOYCACHAAUAA5wIAIeEBAACMA-EBIuMBAACNA-MBIuUBAACOA-UBIuYBAQDmAgAhBwgAAJADACC8AQEA5gIAIcABQADnAgAh4QEAAIwD4QEi4wEAAI0D4wEi5QEAAI4D5QEi5gEBAOYCACEHCAAAngMAILwBAQAAAAHAAUAAAAAB4QEAAADhAQLjAQAAAOMBAuUBAAAA5QEC5gEBAAAAAQwFAADpAwAgCAAA3gMAIAsAAN8DACAMAADgAwAgvAEBAAAAAcABQAAAAAHeAQgAAAAB5wEBAAAAAesBAgAAAAHsAQEAAAAB7QEBAAAAAe4BAQAAAAECAAAABQAgHQAAtAQAIAMAAAAFACAdAAC0BAAgHgAAswQAIAEWAADFBAAwAgAAAAUAIBYAALMEACACAAAAtAMAIBYAALIEACAIvAEBAOYCACHAAUAA5wIAId4BCACEAwAh5wEBAOYCACHrAQIA-gIAIewBAQDmAgAh7QEBAOwCACHuAQEA5gIAIQwFAADoAwAgCAAAuAMAIAsAALkDACAMAAC6AwAgvAEBAOYCACHAAUAA5wIAId4BCACEAwAh5wEBAOYCACHrAQIA-gIAIewBAQDmAgAh7QEBAOwCACHuAQEA5gIAIQwFAADpAwAgCAAA3gMAIAsAAN8DACAMAADgAwAgvAEBAAAAAcABQAAAAAHeAQgAAAAB5wEBAAAAAesBAgAAAAHsAQEAAAAB7QEBAAAAAe4BAQAAAAEEHQAArAQAMPgBAACtBAAw-gEAAK8EACD-AQAAsAMAMAQdAACgBAAw-AEAAKEEADD6AQAAowQAIP4BAACkBAAwBB0AAJcEADD4AQAAmAQAMPoBAACaBAAg_gEAAMsDADAEHQAAjgQAMPgBAACPBAAw-gEAAJEEACD-AQAAvwMAMAQdAACCBAAw-AEAAIMEADD6AQAAhQQAIP4BAACGBAAwBB0AAPYDADD4AQAA9wMAMPoBAAD5AwAg_gEAAPoDADAAAAAAAAcDAADiAwAgCwAAvAQAIA0AALsEACAOAAC9BAAgDwAAvgQAIBAAAL8EACDtAQAA6AIAIAAGBQAAxAQAIAYAAMAEACAIAADBBAAgCwAAvAQAIAwAAL0EACDtAQAA6AIAIAIHAADABAAgCAAAwQQAIAEDAADiAwAgCLwBAQAAAAHAAUAAAAAB3gEIAAAAAecBAQAAAAHrAQIAAAAB7AEBAAAAAe0BAQAAAAHuAQEAAAABBrwBAQAAAAHAAUAAAAAB4QEAAADhAQLjAQAAAOMBAuUBAAAA5QEC5gEBAAAAAQW8AQEAAAABwAFAAAAAAdoBAQAAAAHbAQIAAAAB3AEBAAAAAQO8AQEAAAAB2gEBAAAAAd8BAgAAAAEHvAEBAAAAAb8BQAAAAAHAAUAAAAABwQFAAAAAAdcBAQAAAAHYAQEAAAAB2QEBAAAAAQy8AQEAAAABwAFAAAAAAcEBQAAAAAHNAQEAAAABzgEBAAAAAdABAQAAAAHRAQEAAAAB0gEBAAAAAdMBQAAAAAHUAUAAAAAB1QEBAAAAAdYBAQAAAAEDvAEBAAAAAcABQAAAAAHnAQEAAAABAgAAAFsAIB0AAMsEACADAAAAXgAgHQAAywQAIB4AAM8EACAFAAAAXgAgFgAAzwQAILwBAQDmAgAhwAFAAOcCACHnAQEA5gIAIQO8AQEA5gIAIcABQADnAgAh5wEBAOYCACEOCwAAtwQAIA0AALYEACAOAAC4BAAgDwAAuQQAIBAAALoEACC8AQEAAAABwAFAAAAAAcEBQAAAAAHhAQAAAPQBAucBAQAAAAHtAQEAAAAB8AEBAAAAAfIBAAAA8gEC9AEgAAAAAQIAAAABACAdAADQBAAgBLwBAQAAAAHdAQEAAAAB3gEIAAAAAd8BAgAAAAEFvAEBAAAAAcABQAAAAAHPAQEAAAAB2wECAAAAAdwBAQAAAAEDvAEBAAAAAc8BAQAAAAHfAQIAAAABAwAAAC8AIB0AANAEACAeAADXBAAgEAAAAC8AIAsAAPIDACANAADxAwAgDgAA8wMAIA8AAPQDACAQAAD1AwAgFgAA1wQAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIeEBAADuA_QBIucBAQDmAgAh7QEBAOwCACHwAQEA5gIAIfIBAADtA_IBIvQBIADvAwAhDgsAAPIDACANAADxAwAgDgAA8wMAIA8AAPQDACAQAAD1AwAgvAEBAOYCACHAAUAA5wIAIcEBQADnAgAh4QEAAO4D9AEi5wEBAOYCACHtAQEA7AIAIfABAQDmAgAh8gEAAO0D8gEi9AEgAO8DACEIvAEBAAAAAcABQAAAAAHeAQgAAAAB5wEBAAAAAesBAgAAAAHsAQEAAAAB7QEBAAAAAe8BAQAAAAENBQAA6QMAIAYAAN0DACAIAADeAwAgCwAA3wMAILwBAQAAAAHAAUAAAAAB3gEIAAAAAecBAQAAAAHrAQIAAAAB7AEBAAAAAe0BAQAAAAHuAQEAAAAB7wEBAAAAAQIAAAAFACAdAADZBAAgDgMAALUEACALAAC3BAAgDQAAtgQAIA8AALkEACAQAAC6BAAgvAEBAAAAAcABQAAAAAHBAUAAAAAB4QEAAAD0AQLnAQEAAAAB7QEBAAAAAfABAQAAAAHyAQAAAPIBAvQBIAAAAAECAAAAAQAgHQAA2wQAIAMAAAADACAdAADZBAAgHgAA3wQAIA8AAAADACAFAADoAwAgBgAAtwMAIAgAALgDACALAAC5AwAgFgAA3wQAILwBAQDmAgAhwAFAAOcCACHeAQgAhAMAIecBAQDmAgAh6wECAPoCACHsAQEA5gIAIe0BAQDsAgAh7gEBAOYCACHvAQEA5gIAIQ0FAADoAwAgBgAAtwMAIAgAALgDACALAAC5AwAgvAEBAOYCACHAAUAA5wIAId4BCACEAwAh5wEBAOYCACHrAQIA-gIAIewBAQDmAgAh7QEBAOwCACHuAQEA5gIAIe8BAQDmAgAhAwAAAC8AIB0AANsEACAeAADiBAAgEAAAAC8AIAMAAPADACALAADyAwAgDQAA8QMAIA8AAPQDACAQAAD1AwAgFgAA4gQAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIeEBAADuA_QBIucBAQDmAgAh7QEBAOwCACHwAQEA5gIAIfIBAADtA_IBIvQBIADvAwAhDgMAAPADACALAADyAwAgDQAA8QMAIA8AAPQDACAQAAD1AwAgvAEBAOYCACHAAUAA5wIAIcEBQADnAgAh4QEAAO4D9AEi5wEBAOYCACHtAQEA7AIAIfABAQDmAgAh8gEAAO0D8gEi9AEgAO8DACEOAwAAtQQAIAsAALcEACAOAAC4BAAgDwAAuQQAIBAAALoEACC8AQEAAAABwAFAAAAAAcEBQAAAAAHhAQAAAPQBAucBAQAAAAHtAQEAAAAB8AEBAAAAAfIBAAAA8gEC9AEgAAAAAQIAAAABACAdAADjBAAgBLwBAQAAAAHaAQEAAAAB3gEIAAAAAd8BAgAAAAEDAAAALwAgHQAA4wQAIB4AAOgEACAQAAAALwAgAwAA8AMAIAsAAPIDACAOAADzAwAgDwAA9AMAIBAAAPUDACAWAADoBAAgvAEBAOYCACHAAUAA5wIAIcEBQADnAgAh4QEAAO4D9AEi5wEBAOYCACHtAQEA7AIAIfABAQDmAgAh8gEAAO0D8gEi9AEgAO8DACEOAwAA8AMAIAsAAPIDACAOAADzAwAgDwAA9AMAIBAAAPUDACC8AQEA5gIAIcABQADnAgAhwQFAAOcCACHhAQAA7gP0ASLnAQEA5gIAIe0BAQDsAgAh8AEBAOYCACHyAQAA7QPyASL0ASAA7wMAIQ0FAADpAwAgBgAA3QMAIAsAAN8DACAMAADgAwAgvAEBAAAAAcABQAAAAAHeAQgAAAAB5wEBAAAAAesBAgAAAAHsAQEAAAAB7QEBAAAAAe4BAQAAAAHvAQEAAAABAgAAAAUAIB0AAOkEACAIBwAAnQMAILwBAQAAAAHAAUAAAAABzwEBAAAAAeEBAAAA4QEC4wEAAADjAQLlAQAAAOUBAuYBAQAAAAECAAAAHAAgHQAA6wQAIAMAAAADACAdAADpBAAgHgAA7wQAIA8AAAADACAFAADoAwAgBgAAtwMAIAsAALkDACAMAAC6AwAgFgAA7wQAILwBAQDmAgAhwAFAAOcCACHeAQgAhAMAIecBAQDmAgAh6wECAPoCACHsAQEA5gIAIe0BAQDsAgAh7gEBAOYCACHvAQEA5gIAIQ0FAADoAwAgBgAAtwMAIAsAALkDACAMAAC6AwAgvAEBAOYCACHAAUAA5wIAId4BCACEAwAh5wEBAOYCACHrAQIA-gIAIewBAQDmAgAh7QEBAOwCACHuAQEA5gIAIe8BAQDmAgAhAwAAABoAIB0AAOsEACAeAADyBAAgCgAAABoAIAcAAI8DACAWAADyBAAgvAEBAOYCACHAAUAA5wIAIc8BAQDmAgAh4QEAAIwD4QEi4wEAAI0D4wEi5QEAAI4D5QEi5gEBAOYCACEIBwAAjwMAILwBAQDmAgAhwAFAAOcCACHPAQEA5gIAIeEBAACMA-EBIuMBAACNA-MBIuUBAACOA-UBIuYBAQDmAgAhDQUAAOkDACAGAADdAwAgCAAA3gMAIAwAAOADACC8AQEAAAABwAFAAAAAAd4BCAAAAAHnAQEAAAAB6wECAAAAAewBAQAAAAHtAQEAAAAB7gEBAAAAAe8BAQAAAAECAAAABQAgHQAA8wQAIA4DAAC1BAAgDQAAtgQAIA4AALgEACAPAAC5BAAgEAAAugQAILwBAQAAAAHAAUAAAAABwQFAAAAAAeEBAAAA9AEC5wEBAAAAAe0BAQAAAAHwAQEAAAAB8gEAAADyAQL0ASAAAAABAgAAAAEAIB0AAPUEACADAAAAAwAgHQAA8wQAIB4AAPkEACAPAAAAAwAgBQAA6AMAIAYAALcDACAIAAC4AwAgDAAAugMAIBYAAPkEACC8AQEA5gIAIcABQADnAgAh3gEIAIQDACHnAQEA5gIAIesBAgD6AgAh7AEBAOYCACHtAQEA7AIAIe4BAQDmAgAh7wEBAOYCACENBQAA6AMAIAYAALcDACAIAAC4AwAgDAAAugMAILwBAQDmAgAhwAFAAOcCACHeAQgAhAMAIecBAQDmAgAh6wECAPoCACHsAQEA5gIAIe0BAQDsAgAh7gEBAOYCACHvAQEA5gIAIQMAAAAvACAdAAD1BAAgHgAA_AQAIBAAAAAvACADAADwAwAgDQAA8QMAIA4AAPMDACAPAAD0AwAgEAAA9QMAIBYAAPwEACC8AQEA5gIAIcABQADnAgAhwQFAAOcCACHhAQAA7gP0ASLnAQEA5gIAIe0BAQDsAgAh8AEBAOYCACHyAQAA7QPyASL0ASAA7wMAIQ4DAADwAwAgDQAA8QMAIA4AAPMDACAPAAD0AwAgEAAA9QMAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIeEBAADuA_QBIucBAQDmAgAh7QEBAOwCACHwAQEA5gIAIfIBAADtA_IBIvQBIADvAwAhDgMAALUEACALAAC3BAAgDQAAtgQAIA4AALgEACAQAAC6BAAgvAEBAAAAAcABQAAAAAHBAUAAAAAB4QEAAAD0AQLnAQEAAAAB7QEBAAAAAfABAQAAAAHyAQAAAPIBAvQBIAAAAAECAAAAAQAgHQAA_QQAIAMAAAAvACAdAAD9BAAgHgAAgQUAIBAAAAAvACADAADwAwAgCwAA8gMAIA0AAPEDACAOAADzAwAgEAAA9QMAIBYAAIEFACC8AQEA5gIAIcABQADnAgAhwQFAAOcCACHhAQAA7gP0ASLnAQEA5gIAIe0BAQDsAgAh8AEBAOYCACHyAQAA7QPyASL0ASAA7wMAIQ4DAADwAwAgCwAA8gMAIA0AAPEDACAOAADzAwAgEAAA9QMAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIeEBAADuA_QBIucBAQDmAgAh7QEBAOwCACHwAQEA5gIAIfIBAADtA_IBIvQBIADvAwAhDgMAALUEACALAAC3BAAgDQAAtgQAIA4AALgEACAPAAC5BAAgvAEBAAAAAcABQAAAAAHBAUAAAAAB4QEAAAD0AQLnAQEAAAAB7QEBAAAAAfABAQAAAAHyAQAAAPIBAvQBIAAAAAECAAAAAQAgHQAAggUAIAMAAAAvACAdAACCBQAgHgAAhgUAIBAAAAAvACADAADwAwAgCwAA8gMAIA0AAPEDACAOAADzAwAgDwAA9AMAIBYAAIYFACC8AQEA5gIAIcABQADnAgAhwQFAAOcCACHhAQAA7gP0ASLnAQEA5gIAIe0BAQDsAgAh8AEBAOYCACHyAQAA7QPyASL0ASAA7wMAIQ4DAADwAwAgCwAA8gMAIA0AAPEDACAOAADzAwAgDwAA9AMAILwBAQDmAgAhwAFAAOcCACHBAUAA5wIAIeEBAADuA_QBIucBAQDmAgAh7QEBAOwCACHwAQEA5gIAIfIBAADtA_IBIvQBIADvAwAhBwMGAgQADQseCA0dBg4fCQ8jCxAnDAYEAAoFAAMGAAEIDAULEggMFgkCAwcCBAAEAQMIAAIJAAYKAAIDBAAHBwABCA0FAQgOAAIHAAEKAAICBwABCgACAwgXAAsYAAwZAAEHAAEBBwABBgMoAAsqAA0pAA4rAA8sABAtAAAAAAMEABIjABMkABQAAAADBAASIwATJAAUAgUAAwYAAQIFAAMGAAEFBAAZIwAcJAAdNQAaNgAbAAAAAAAFBAAZIwAcJAAdNQAaNgAbAAADBAAiIwAjJAAkAAAAAwQAIiMAIyQAJAIHAAEKAAICBwABCgACBQQAKSMALCQALTUAKjYAKwAAAAAABQQAKSMALCQALTUAKjYAKwEHAAEBBwABAwQAMiMAMyQANAAAAAMEADIjADMkADQCCQAGCgACAgkABgoAAgUEADkjADwkAD01ADo2ADsAAAAAAAUEADkjADwkAD01ADo2ADsCBwABCgACAgcAAQoAAgUEAEIjAEUkAEY1AEM2AEQAAAAAAAUEAEIjAEUkAEY1AEM2AEQBBwABAQcAAQMEAEsjAEwkAE0AAAADBABLIwBMJABNAQcAAQEHAAEDBABSIwBTJABUAAAAAwQAUiMAUyQAVAAAAAMEAFojAFskAFwAAAADBABaIwBbJABcEQIBEi4BEzEBFDIBFTMBFzUBGDcOGTgPGjoBGzwOHD0QHz4BID8BIUAOJUMRJkQVJ0UCKEYCKUcCKkgCK0kCLEsCLU0OLk4WL1ACMFIOMVMXMlQCM1UCNFYON1kYOFoeOVwDOl0DO2ADPGEDPWIDPmQDP2YOQGcfQWkDQmsOQ2wgRG0DRW4DRm8OR3IhSHMlSXQJSnUJS3YJTHcJTXgJTnoJT3wOUH0mUX8JUoEBDlOCASdUgwEJVYQBCVaFAQ5XiAEoWIkBLlmKAQZaiwEGW4wBBlyNAQZdjgEGXpABBl-SAQ5gkwEvYZUBBmKXAQ5jmAEwZJkBBmWaAQZmmwEOZ54BMWifATVpoAEFaqEBBWuiAQVsowEFbaQBBW6mAQVvqAEOcKkBNnGrAQVyrQEOc64BN3SvAQV1sAEFdrEBDne0ATh4tQE-ebYBCHq3AQh7uAEIfLkBCH26AQh-vAEIf74BDoABvwE_gQHBAQiCAcMBDoMBxAFAhAHFAQiFAcYBCIYBxwEOhwHKAUGIAcsBR4kBzAELigHNAQuLAc4BC4wBzwELjQHQAQuOAdIBC48B1AEOkAHVAUiRAdcBC5IB2QEOkwHaAUmUAdsBC5UB3AELlgHdAQ6XAeABSpgB4QFOmQHiAQyaAeMBDJsB5AEMnAHlAQydAeYBDJ4B6AEMnwHqAQ6gAesBT6EB7QEMogHvAQ6jAfABUKQB8QEMpQHyAQymAfMBDqcB9gFRqAH3AVWpAfkBVqoB-gFWqwH9AVasAf4BVq0B_wFWrgGBAlavAYMCDrABhAJXsQGGAlayAYgCDrMBiQJYtAGKAla1AYsCVrYBjAIOtwGPAlm4AZACXQ"
};
async function decodeBase64AsWasm(wasmBase64) {
  const { Buffer: Buffer2 } = await import("buffer");
  const wasmArray = Buffer2.from(wasmBase64, "base64");
  return new WebAssembly.Module(wasmArray);
}
config.compilerWasm = {
  getRuntime: async () => await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.mjs"),
  getQueryCompilerWasmModule: async () => {
    const { wasm } = await import("@prisma/client/runtime/query_compiler_fast_bg.postgresql.wasm-base64.mjs");
    return await decodeBase64AsWasm(wasm);
  },
  importName: "./query_compiler_fast_bg.js"
};
function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}

// generated/prisma/internal/prismaNamespace.ts
var prismaNamespace_exports = {};
__export(prismaNamespace_exports, {
  AccountScalarFieldEnum: () => AccountScalarFieldEnum,
  AnyNull: () => AnyNull2,
  CartScalarFieldEnum: () => CartScalarFieldEnum,
  CategoryScalarFieldEnum: () => CategoryScalarFieldEnum,
  DbNull: () => DbNull2,
  Decimal: () => Decimal2,
  JsonNull: () => JsonNull2,
  MedicineScalarFieldEnum: () => MedicineScalarFieldEnum,
  ModelName: () => ModelName,
  NullTypes: () => NullTypes2,
  NullsOrder: () => NullsOrder,
  OrderItemScalarFieldEnum: () => OrderItemScalarFieldEnum,
  OrderScalarFieldEnum: () => OrderScalarFieldEnum,
  PrismaClientInitializationError: () => PrismaClientInitializationError2,
  PrismaClientKnownRequestError: () => PrismaClientKnownRequestError2,
  PrismaClientRustPanicError: () => PrismaClientRustPanicError2,
  PrismaClientUnknownRequestError: () => PrismaClientUnknownRequestError2,
  PrismaClientValidationError: () => PrismaClientValidationError2,
  QueryMode: () => QueryMode,
  ReviewScalarFieldEnum: () => ReviewScalarFieldEnum,
  SessionScalarFieldEnum: () => SessionScalarFieldEnum,
  SortOrder: () => SortOrder,
  Sql: () => Sql2,
  TransactionIsolationLevel: () => TransactionIsolationLevel,
  UserScalarFieldEnum: () => UserScalarFieldEnum,
  VerificationScalarFieldEnum: () => VerificationScalarFieldEnum,
  defineExtension: () => defineExtension,
  empty: () => empty2,
  getExtensionContext: () => getExtensionContext,
  join: () => join2,
  prismaVersion: () => prismaVersion,
  raw: () => raw2,
  sql: () => sql
});
import * as runtime2 from "@prisma/client/runtime/client";
var PrismaClientKnownRequestError2 = runtime2.PrismaClientKnownRequestError;
var PrismaClientUnknownRequestError2 = runtime2.PrismaClientUnknownRequestError;
var PrismaClientRustPanicError2 = runtime2.PrismaClientRustPanicError;
var PrismaClientInitializationError2 = runtime2.PrismaClientInitializationError;
var PrismaClientValidationError2 = runtime2.PrismaClientValidationError;
var sql = runtime2.sqltag;
var empty2 = runtime2.empty;
var join2 = runtime2.join;
var raw2 = runtime2.raw;
var Sql2 = runtime2.Sql;
var Decimal2 = runtime2.Decimal;
var getExtensionContext = runtime2.Extensions.getExtensionContext;
var prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
};
var NullTypes2 = {
  DbNull: runtime2.NullTypes.DbNull,
  JsonNull: runtime2.NullTypes.JsonNull,
  AnyNull: runtime2.NullTypes.AnyNull
};
var DbNull2 = runtime2.DbNull;
var JsonNull2 = runtime2.JsonNull;
var AnyNull2 = runtime2.AnyNull;
var ModelName = {
  User: "User",
  Medicine: "Medicine",
  Category: "Category",
  Cart: "Cart",
  Order: "Order",
  OrderItem: "OrderItem",
  Review: "Review",
  Session: "Session",
  Account: "Account",
  Verification: "Verification"
};
var TransactionIsolationLevel = runtime2.makeStrictEnum({
  ReadUncommitted: "ReadUncommitted",
  ReadCommitted: "ReadCommitted",
  RepeatableRead: "RepeatableRead",
  Serializable: "Serializable"
});
var UserScalarFieldEnum = {
  id: "id",
  name: "name",
  email: "email",
  role: "role",
  status: "status",
  createdAt: "createdAt",
  emailVerified: "emailVerified",
  image: "image",
  updatedAt: "updatedAt"
};
var MedicineScalarFieldEnum = {
  id: "id",
  name: "name",
  price: "price",
  stock: "stock",
  description: "description",
  image: "image",
  createdAt: "createdAt",
  categoryId: "categoryId",
  sellerId: "sellerId"
};
var CategoryScalarFieldEnum = {
  id: "id",
  name: "name",
  createdAt: "createdAt"
};
var CartScalarFieldEnum = {
  id: "id",
  userId: "userId",
  medicineId: "medicineId",
  quantity: "quantity"
};
var OrderScalarFieldEnum = {
  id: "id",
  userId: "userId",
  status: "status",
  paymentMethod: "paymentMethod",
  paymentStatus: "paymentStatus",
  address: "address",
  createdAt: "createdAt"
};
var OrderItemScalarFieldEnum = {
  id: "id",
  orderId: "orderId",
  medicineId: "medicineId",
  price: "price",
  quantity: "quantity"
};
var ReviewScalarFieldEnum = {
  id: "id",
  userId: "userId",
  medicineId: "medicineId",
  rating: "rating",
  comment: "comment",
  createdAt: "createdAt"
};
var SessionScalarFieldEnum = {
  id: "id",
  expiresAt: "expiresAt",
  token: "token",
  createdAt: "createdAt",
  updatedAt: "updatedAt",
  ipAddress: "ipAddress",
  userAgent: "userAgent",
  userId: "userId"
};
var AccountScalarFieldEnum = {
  id: "id",
  accountId: "accountId",
  providerId: "providerId",
  userId: "userId",
  accessToken: "accessToken",
  refreshToken: "refreshToken",
  idToken: "idToken",
  accessTokenExpiresAt: "accessTokenExpiresAt",
  refreshTokenExpiresAt: "refreshTokenExpiresAt",
  scope: "scope",
  password: "password",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var VerificationScalarFieldEnum = {
  id: "id",
  identifier: "identifier",
  value: "value",
  expiresAt: "expiresAt",
  createdAt: "createdAt",
  updatedAt: "updatedAt"
};
var SortOrder = {
  asc: "asc",
  desc: "desc"
};
var QueryMode = {
  default: "default",
  insensitive: "insensitive"
};
var NullsOrder = {
  first: "first",
  last: "last"
};
var defineExtension = runtime2.Extensions.defineExtension;

// generated/prisma/enums.ts
var OrderStatus = {
  PLACED: "PLACED",
  PROCESSING: "PROCESSING",
  SHIPPED: "SHIPPED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED"
};

// generated/prisma/client.ts
globalThis["__dirname"] = path.dirname(fileURLToPath(import.meta.url));
var PrismaClient = getPrismaClientClass();

// src/lib/prisma.ts
import { PrismaPg } from "@prisma/adapter-pg";
var connectionString = process.env.DATABASE_URL;
var adapter = new PrismaPg({ connectionString });
var prisma = new PrismaClient({ adapter });

// src/lib/auth.ts
import nodemailer from "nodemailer";
var transporter = nodemailer.createTransport({
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: process.env.APP_USER,
    pass: process.env.APP_PASS
  }
});
var auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: "postgresql"
  }),
  trustedOrigins: [process.env.APP_URL],
  user: {
    additionalFields: {
      role: {
        type: "string",
        defaultValue: "USER",
        required: false
      },
      phone: {
        type: "string",
        required: false
      },
      status: {
        type: "string",
        defaultValue: "ACTIVE",
        required: false
      }
    }
  },
  emailAndPassword: {
    enabled: true,
    autoSignIn: false,
    requireEmailVerification: true
  },
  emailVerification: {
    sendOnSignUp: true,
    autoSignInAfterVerification: true,
    sendVerificationEmail: async ({ user, url, token }, request) => {
      try {
        const verificationUrl = `${process.env.APP_URL}/verify-email?token=${token}`;
        const info = await transporter.sendMail({
          from: `"Medi Store" <${process.env.APP_USER}>`,
          to: user.email,
          subject: "Verify your email",
          html: `
          <!DOCTYPE html>
          <html>
            <body style="margin:0;padding:0;background:#f4f6fa;font-family:Arial,sans-serif;">
              <table width="100%" cellpadding="0" cellspacing="0">
                <tr>
                  <td align="center" style="padding:40px 0;">
                    <table width="100%" style="max-width:480px;background:#ffffff;border-radius:8px;padding:32px;text-align:center;box-shadow:0 2px 10px rgba(0,0,0,0.05);">
                      <tr>
                        <td>
                          <!-- Logo -->
                          <img src="https://cdn-icons-png.flaticon.com/512/2965/2965567.png" 
                               alt="MediStore Logo" 
                               width="80" 
                               style="margin-bottom:16px;" />
          
                          <!-- App Name -->
                          <h1 style="margin:0 0 12px;color:#4f46e5;font-size:28px;font-weight:bold;">MediStore</h1>
                          <h2 style="margin:0 0 16px;color:#111;font-size:20px;">Verify your email</h2>
          
                          <p style="margin:0 0 24px;color:#555;font-size:14px;line-height:1.5;">
                            Thank you for signing up to <strong>MediStore</strong>! Please click the button below to verify your email address and start managing your medicines and orders.
                          </p>
          
                          <a
                            href="${verificationUrl}"
                            style="
                              display:inline-block;
                              padding:14px 24px;
                              background:#4f46e5;
                              color:#ffffff;
                              text-decoration:none;
                              border-radius:6px;
                              font-size:16px;
                              font-weight:600;
                            "
                          >
                            Verify Email
                          </a>
          
                          <p style="margin:24px 0 0;font-size:12px;color:#888;line-height:1.4;">
                            If you didn\u2019t create an account on <strong>MediStore</strong>, you can safely ignore this email.
                          </p>
          
                          <p style="margin:16px 0 0;font-size:12px;color:#aaa;">
                            &copy; ${(/* @__PURE__ */ new Date()).getFullYear()} MediStore. All rights reserved.
                          </p>
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </body>
          </html>
          `
        });
        console.log("Message send", info.messageId);
      } catch (error) {
        console.error(error);
        throw error;
      }
    }
  },
  socialProviders: {
    google: {
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      accessType: "offline",
      prompt: "select_account consent"
    }
  }
});

// src/middlewares/appErrors.ts
var AppError = class extends Error {
  statusCode;
  constructor(message, statusCode) {
    super(message);
    this.statusCode = statusCode;
  }
};
var appErrors_default = AppError;

// src/middlewares/notFound.ts
function notFound(req, res, next) {
  next(new appErrors_default(`Route not found: ${req.originalUrl}`, 404));
}

// src/middlewares/globalErrorHandler.ts
var errorHandler = (err, req, res, next) => {
  let statusCode = 500;
  let message = "Internal Server Error";
  let errors = null;
  if (err instanceof prismaNamespace_exports.PrismaClientValidationError) {
    statusCode = 400;
    message = "Invalid data provided";
  } else if (err instanceof prismaNamespace_exports.PrismaClientKnownRequestError) {
    switch (err.code) {
      case "P2002":
        statusCode = 409;
        message = `Duplicate value for field: ${err.meta?.target}`;
        break;
      case "P2025":
        statusCode = 404;
        message = "Record not found";
        break;
      case "P2003":
        statusCode = 400;
        message = "Foreign key constraint failed";
        break;
      default:
        statusCode = 400;
        message = "Database request error";
    }
  } else if (err instanceof prismaNamespace_exports.PrismaClientInitializationError) {
    statusCode = 500;
    message = "Database connection failed";
  } else if (err instanceof prismaNamespace_exports.PrismaClientRustPanicError) {
    statusCode = 500;
    message = "Unexpected database error";
  } else if (err.statusCode && err.message) {
    statusCode = err.statusCode;
    message = err.message;
  }
  res.status(statusCode).json({
    success: false,
    message,
    ...process.env.NODE_ENV === "development" && {
      stack: err.stack,
      error: err
    }
  });
};
var globalErrorHandler_default = errorHandler;

// src/modules/medicine/medicine.routes.ts
import express from "express";

// src/middlewares/auth.ts
var auth2 = (...roles) => {
  return async (req, res, next) => {
    try {
      const session = await auth.api.getSession({
        headers: req.headers
      });
      if (!session) {
        return res.status(401).json({
          success: false,
          message: "Your are not authorized!"
        });
      }
      if (!session.user.emailVerified) {
        return res.status(403).json({
          success: false,
          message: "Email verification required, please verify your email"
        });
      }
      const dbUser = await prisma.user.findUnique({
        where: { id: session.user.id }
      });
      if (!dbUser) {
        return res.status(401).json({ message: "Your are not authorized!" });
      }
      req.user = {
        id: dbUser.id,
        email: dbUser.email,
        name: dbUser.name,
        role: dbUser.role,
        emailVerified: session.user.emailVerified
      };
      if (roles.length && !roles.includes(req.user.role)) {
        return res.status(403).json({
          success: false,
          message: "Forbidden! You don`t have permission to access this resources"
        });
      }
      next();
    } catch (error) {
      next(error);
    }
  };
};
var auth_default = auth2;

// src/modules/medicine/medicine.service.ts
var createMedicine = async (data, sellerId) => {
  const result = await prisma.medicine.create({
    data: {
      ...data,
      sellerId
    }
  });
  return result;
};
var getAllMedicines = async (query) => {
  const { search, categoryId } = query;
  const where = {};
  if (search) {
    where.name = {
      contains: search.trim(),
      mode: "insensitive"
    };
  }
  if (categoryId) {
    where.categoryId = categoryId;
  }
  const result = await prisma.medicine.findMany({
    where,
    include: {
      category: true,
      seller: {
        select: {
          id: true,
          name: true
        }
      }
    }
  });
  return result;
};
var getMedicineById = async (id) => {
  const result = await prisma.medicine.findUnique({
    where: { id },
    include: {
      category: true,
      seller: {
        select: {
          id: true,
          name: true
        }
      },
      reviews: true
    }
  });
  return result;
};
var getSellerMedicines = async (sellerId) => {
  const result = await prisma.medicine.findMany({
    where: {
      sellerId
    }
  });
  return result;
};
var updateMedicine = async (medicineId, sellerId, data) => {
  const medicine = await prisma.medicine.findUnique({
    where: { id: medicineId }
  });
  if (!medicine) {
    throw new appErrors_default("Medicine not found", 404);
  }
  if (medicine.sellerId !== sellerId) {
    throw new appErrors_default(
      "Forbidden! You cannot update another seller's medicine",
      403
    );
  }
  return await prisma.medicine.update({
    where: { id: medicineId },
    data
  });
};
var deleteMedicine = async (medicineId, sellerId) => {
  const medicine = await prisma.medicine.findUnique({
    where: { id: medicineId }
  });
  if (!medicine) {
    throw new appErrors_default("medicine not found", 404);
  }
  if (medicine.sellerId !== sellerId) {
    throw new appErrors_default(
      "Forbidden! You cannot delete another seller's medicine",
      403
    );
  }
  await prisma.medicine.delete({ where: { id: medicineId } });
  return null;
};
var medicineServices = {
  createMedicine,
  getAllMedicines,
  getMedicineById,
  getSellerMedicines,
  updateMedicine,
  deleteMedicine
};

// src/modules/medicine/medicine.controller.ts
var createMedicine2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      throw new appErrors_default("Invalid medicine data", 401);
    }
    const result = await medicineServices.createMedicine(
      req.body,
      user.id
    );
    res.status(201).json({
      success: true,
      message: "Medicine created successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllMedicines2 = async (req, res, next) => {
  try {
    const result = await medicineServices.getAllMedicines(req.query);
    res.status(200).json({
      success: true,
      message: "Medicines retrieved successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getMedicineById2 = async (req, res, next) => {
  try {
    const { id } = req.params;
    const result = await medicineServices.getMedicineById(id);
    if (!result) {
      throw new appErrors_default("Medicine not found", 404);
    }
    res.status(200).json({
      success: true,
      message: "Medicine retrieved successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getSellerMedicines2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    const result = await medicineServices.getSellerMedicines(user.id);
    res.status(200).json({
      success: true,
      message: "Seller medicines retrieved successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var updateMedicine2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { id } = req.params;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    if (!id || Array.isArray(id)) {
      throw new appErrors_default("Invalid medicine id", 400);
    }
    const result = await medicineServices.updateMedicine(
      id,
      user.id,
      req.body
    );
    res.status(200).json({
      success: true,
      message: "Medicine updated successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var deleteMedicine2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { id } = req.params;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    await medicineServices.deleteMedicine(id, user.id);
    res.status(200).json({
      success: true,
      message: "Medicine deleted successfully"
    });
  } catch (error) {
    next(error);
  }
};
var medicineController = {
  createMedicine: createMedicine2,
  getAllMedicines: getAllMedicines2,
  getMedicineById: getMedicineById2,
  getSellerMedicines: getSellerMedicines2,
  updateMedicine: updateMedicine2,
  deleteMedicine: deleteMedicine2
};

// src/modules/medicine/medicine.routes.ts
var router = express.Router();
router.post("/", auth_default("SELLER" /* SELLER */), medicineController.createMedicine);
router.get("/", medicineController.getAllMedicines);
router.get("/:id", medicineController.getMedicineById);
router.get(
  "/seller/my-medicines",
  auth_default("SELLER" /* SELLER */, "ADMIN" /* ADMIN */),
  medicineController.getSellerMedicines
);
router.patch("/:id", auth_default("SELLER" /* SELLER */), medicineController.updateMedicine);
router.delete("/:id", auth_default("SELLER" /* SELLER */), medicineController.deleteMedicine);
var medicineRouter = router;

// src/modules/category/category.route.ts
import express2 from "express";

// src/modules/category/category.service.ts
var createCategory = async (data) => {
  const result = await prisma.category.create({
    data: {
      ...data
    }
  });
  return result;
};
var getCategories = async () => {
  const categories = await prisma.category.findMany({
    orderBy: { createdAt: "desc" }
  });
  return categories;
};
var updateCategory = async (categoryId, name) => {
  return prisma.category.update({
    where: { id: categoryId },
    data: { name }
  });
};
var deleteCategory = async (categoryId) => {
  return prisma.category.delete({ where: { id: categoryId } });
};
var categoryServices = {
  createCategory,
  getCategories,
  updateCategory,
  deleteCategory
};

// src/modules/category/category.controller.ts
var createCategory2 = async (req, res, next) => {
  try {
    const { name } = req.body;
    if (!name) throw new appErrors_default("Category name is required", 400);
    const result = await categoryServices.createCategory({ name });
    res.status(201).json({
      success: true,
      message: "Category created successfully",
      category: result
    });
  } catch (error) {
    next(error);
  }
};
var getAllCategories = async (_req, res, next) => {
  try {
    const categories = await categoryServices.getCategories();
    res.status(200).json({
      success: true,
      categories
    });
  } catch (error) {
    next(error);
  }
};
var editCategory = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { name } = req.body;
    console.log("osud name", name);
    const category = await categoryServices.updateCategory(id, name);
    res.status(200).json({ success: true, data: category });
  } catch (error) {
    next(error);
  }
};
var removeCategory = async (req, res, next) => {
  try {
    const { id } = req.params;
    const category = await categoryServices.deleteCategory(id);
    res.status(200).json({ success: true, data: category });
  } catch (error) {
    next(error);
  }
};
var categoryController = {
  createCategory: createCategory2,
  getAllCategories,
  editCategory,
  removeCategory
};

// src/modules/category/category.route.ts
var router2 = express2.Router();
router2.post("/", auth_default("ADMIN" /* ADMIN */), categoryController.createCategory);
router2.get("/", categoryController.getAllCategories);
router2.patch("/:id", auth_default("ADMIN" /* ADMIN */), categoryController.editCategory);
router2.delete("/:id", auth_default("ADMIN" /* ADMIN */), categoryController.removeCategory);
var categoryRouter = router2;

// src/modules/order/order.router.ts
import express3 from "express";

// src/modules/order/order.service.ts
var createOrder = async (userId, address) => {
  const cartItems = await prisma.cart.findMany({
    where: { userId },
    include: { medicine: true }
  });
  if (cartItems.length === 0) {
    throw new appErrors_default("Cart is empty", 400);
  }
  const totalPrice = cartItems.reduce(
    (sum, item) => sum + item.medicine.price * item.quantity,
    0
  );
  const order = await prisma.order.create({
    data: {
      userId,
      address,
      status: OrderStatus.PLACED,
      paymentMethod: "CASH_ON_DELIVERY",
      paymentStatus: "PENDING"
    }
  });
  const orderItemsData = cartItems.map((item) => ({
    orderId: order.id,
    medicineId: item.medicineId,
    price: item.medicine.price,
    quantity: item.quantity
  }));
  await prisma.orderItem.createMany({
    data: orderItemsData
  });
  await prisma.cart.deleteMany({
    where: { userId }
  });
  return { order, totalPrice };
};
var getMyOrders = async (userId) => {
  return prisma.order.findMany({
    where: { userId },
    include: {
      orderItems: {
        include: {
          medicine: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var getOrderById = async (orderId, userId) => {
  const order = await prisma.order.findUnique({
    where: { id: orderId },
    include: {
      orderItems: {
        include: {
          medicine: true
        }
      }
    }
  });
  if (!order || order.userId !== userId) {
    throw new appErrors_default("Order not found", 404);
  }
  return order;
};
var orderServices = {
  createOrder,
  getMyOrders,
  getOrderById
};

// src/modules/order/order.controller.ts
var createOrder2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { address } = req.body;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    if (!address) {
      throw new appErrors_default("Delivery address is required", 400);
    }
    const result = await orderServices.createOrder(user.id, address);
    res.status(201).json({
      success: true,
      message: "Order placed successfully",
      data: {
        orderId: result.order.id,
        totalPrice: result.totalPrice,
        paymentMethod: result.order.paymentMethod,
        paymentStatus: result.order.paymentStatus,
        status: result.order.status
      }
    });
  } catch (error) {
    next(error);
  }
};
var getMyOrders2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    const result = await orderServices.getMyOrders(user.id);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getOrderById2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { id } = req.params;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    if (!id || typeof id !== "string") {
      throw new appErrors_default("Invalid order id", 400);
    }
    const result = await orderServices.getOrderById(id, user.id);
    res.status(200).json({
      success: true,
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var orderController = {
  createOrder: createOrder2,
  getMyOrders: getMyOrders2,
  getOrderById: getOrderById2
};

// src/modules/order/order.router.ts
var router3 = express3.Router();
router3.post("/", auth_default("CUSTOMER" /* CUSTOMER */), orderController.createOrder);
router3.get("/", auth_default("CUSTOMER" /* CUSTOMER */), orderController.getMyOrders);
router3.get("/:id", auth_default("CUSTOMER" /* CUSTOMER */), orderController.getOrderById);
var orderRouter = router3;

// src/modules/cart/cartRouter.ts
import express4 from "express";

// src/modules/cart/cartServices.ts
var addToCart = async (userId, medicineId, quantity) => {
  const medicine = await prisma.medicine.findUnique({
    where: { id: medicineId }
  });
  if (!medicine) {
    throw new Error("Medicine not found");
  }
  const existing = await prisma.cart.findUnique({
    where: {
      userId_medicineId: {
        userId,
        medicineId
      }
    }
  });
  if (existing) {
    return prisma.cart.update({
      where: { id: existing.id },
      data: {
        quantity: existing.quantity + quantity
      }
    });
  }
  return prisma.cart.create({
    data: {
      userId,
      medicineId,
      quantity
    }
  });
};
var removeFromCart = async (userId, medicineId) => {
  const existing = await prisma.cart.findUnique({
    where: { userId_medicineId: { userId, medicineId } }
  });
  if (!existing) throw new appErrors_default("Item not found in cart", 404);
  return prisma.cart.delete({
    where: { userId_medicineId: { userId, medicineId } }
  });
};
var getCartItems = async (userId) => {
  return prisma.cart.findMany({
    where: { userId },
    include: { medicine: true }
  });
};
var cartServices = {
  addToCart,
  removeFromCart,
  getCartItems
};

// src/modules/cart/cartController.ts
var getCart = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) throw new appErrors_default("Unauthorized", 401);
    const cartItems = await cartServices.getCartItems(user.id);
    const totalPrice = cartItems.reduce(
      (sum, item) => sum + item.medicine.price * item.quantity,
      0
    );
    res.status(200).json({
      success: true,
      data: { cartItems, totalPrice }
    });
  } catch (err) {
    next(err);
  }
};
var addToCart2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { medicineId, quantity } = req.body;
    if (!user) {
      return res.status(401).json({ message: "Unauthorized" });
    }
    const result = await cartServices.addToCart(user.id, medicineId, quantity);
    res.status(201).json({
      success: true,
      message: "Added to cart",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var removeFromCart2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { medicineId } = req.params;
    if (!user) throw new appErrors_default("Unauthorized", 401);
    await cartServices.removeFromCart(user.id, medicineId);
    res.status(200).json({
      success: true,
      message: "Removed from cart"
    });
  } catch (err) {
    next(err);
  }
};
var cartController = {
  addToCart: addToCart2,
  removeFromCart: removeFromCart2,
  getCart
};

// src/modules/cart/cartRouter.ts
var router4 = express4.Router();
router4.post("/add", auth_default("CUSTOMER" /* CUSTOMER */), cartController.addToCart);
router4.delete(
  "/:medicineId",
  auth_default("CUSTOMER" /* CUSTOMER */),
  cartController.removeFromCart
);
router4.get("/", auth_default("CUSTOMER" /* CUSTOMER */), cartController.getCart);
var cartRouter = router4;

// src/modules/seller/seller.routes.ts
import { Router as Router3 } from "express";

// src/modules/seller/seller.service.ts
var getSellerOrders = async (sellerId) => {
  return prisma.order.findMany({
    where: {
      orderItems: {
        some: {
          medicine: {
            sellerId
          }
        }
      }
    },
    include: {
      orderItems: {
        include: {
          medicine: true
        }
      },
      user: true
    }
  });
};
var updateOrderStatus = async (orderId, sellerId, status) => {
  const order = await prisma.order.findUnique({
    where: { id: orderId },
    include: {
      orderItems: {
        include: {
          medicine: true
        }
      }
    }
  });
  if (!order) {
    throw new appErrors_default("Order not found", 404);
  }
  const hasPermission = order.orderItems.some(
    (item) => item.medicine.sellerId === sellerId
  );
  if (!hasPermission) {
    throw new appErrors_default("Forbidden", 403);
  }
  try {
    const updated = await prisma.order.update({
      where: { id: orderId },
      data: { status }
    });
    return updated;
  } catch (err) {
    console.error("Prisma Update Error:", err.message);
    throw new appErrors_default("Failed to update order status", 500);
  }
};
var sellerService = {
  getSellerOrders,
  updateOrderStatus
};

// src/modules/seller/seller.controller.ts
var getSellerOrders2 = async (req, res, next) => {
  try {
    const user = req.user;
    if (!user) throw new appErrors_default("Unauthorized", 401);
    const orders = await sellerService.getSellerOrders(user.id);
    res.status(200).json({
      success: true,
      data: orders
    });
  } catch (err) {
    next(err);
  }
};
var updateOrderStatus2 = async (req, res, next) => {
  try {
    const seller = req.user;
    const { orderId } = req.params;
    const { status } = req.body;
    if (!seller) throw new appErrors_default("Unauthorized", 401);
    const order = await prisma.order.findUnique({
      where: { id: orderId },
      include: { orderItems: { include: { medicine: true } } }
    });
    if (!order) throw new appErrors_default("Order not found", 404);
    const hasPermission = order.orderItems.some(
      (item) => item.medicine.sellerId === seller.id
    );
    if (!hasPermission) throw new appErrors_default("Forbidden", 403);
    const updatedOrder = await prisma.order.update({
      where: { id: orderId },
      data: { status }
    });
    res.status(200).json({
      success: true,
      message: `Order status updated to ${status}`,
      data: updatedOrder
    });
  } catch (err) {
    next(err);
  }
};
var sellerController = {
  getSellerOrders: getSellerOrders2,
  updateOrderStatus: updateOrderStatus2
};

// src/modules/seller/seller.routes.ts
var router5 = Router3();
router5.get("/", auth_default("SELLER" /* SELLER */), sellerController.getSellerOrders);
router5.patch(
  "/:orderId/status/",
  auth_default("SELLER" /* SELLER */),
  sellerController.updateOrderStatus
);
var sellerOrderRouter = router5;

// src/modules/review/review.route.ts
import express5 from "express";

// src/modules/review/review.service.ts
var createReview = async (userId, medicineId, rating, comment) => {
  const hasDeliveredOrder = await prisma.order.findFirst({
    where: {
      userId,
      status: OrderStatus.DELIVERED,
      orderItems: {
        some: {
          medicineId
        }
      }
    }
  });
  if (!hasDeliveredOrder) {
    throw new appErrors_default("You can review only after the order is delivered", 403);
  }
  const existingReview = await prisma.review.findFirst({
    where: {
      userId,
      medicineId
    }
  });
  if (existingReview) {
    throw new appErrors_default("You have already reviewed this medicine", 400);
  }
  const review = await prisma.review.create({
    data: {
      userId,
      medicineId,
      rating,
      comment
    }
  });
  return review;
};
var getReviewsByMedicine = async (medicineId) => {
  return prisma.review.findMany({
    where: { medicineId },
    include: {
      user: {
        select: {
          id: true,
          name: true
        }
      }
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var reviewServices = {
  createReview,
  getReviewsByMedicine
};

// src/modules/review/review.controller.ts
var createReview2 = async (req, res, next) => {
  try {
    const user = req.user;
    const { medicineId, rating, comment } = req.body;
    if (!user) {
      throw new appErrors_default("Unauthorized", 401);
    }
    const result = await reviewServices.createReview(
      user.id,
      medicineId,
      rating,
      comment
    );
    res.status(201).json({
      success: true,
      message: "Review added successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var getReviewsByMedicine2 = async (req, res, next) => {
  try {
    const { medicineId } = req.params;
    const result = await reviewServices.getReviewsByMedicine(
      medicineId
    );
    res.status(200).json({
      success: true,
      message: "Reviews retrieved successfully",
      data: result
    });
  } catch (error) {
    next(error);
  }
};
var reviewController = {
  createReview: createReview2,
  getReviewsByMedicine: getReviewsByMedicine2
};

// src/modules/review/review.route.ts
var router6 = express5.Router();
router6.post("/", auth_default("CUSTOMER" /* CUSTOMER */), reviewController.createReview);
router6.get("/medicine/:medicineId", reviewController.getReviewsByMedicine);
var reviewRouter = router6;

// src/modules/admin/admin.route.ts
import express6 from "express";

// src/modules/admin/admin.service.ts
var getAllUsers = async () => {
  return prisma.user.findMany({
    select: {
      id: true,
      name: true,
      email: true,
      role: true,
      status: true,
      createdAt: true
    },
    orderBy: {
      createdAt: "desc"
    }
  });
};
var updateUserStatus = async (userId, status) => {
  return prisma.user.update({
    where: { id: userId },
    data: { status }
  });
};
var getAllMedicines3 = async () => {
  return prisma.medicine.findMany({
    include: {
      seller: { select: { id: true, name: true, email: true } },
      category: true
    }
  });
};
var deleteMedicineByAdmin = async (medicineId) => {
  return prisma.medicine.delete({
    where: { id: medicineId }
  });
};
var getAllOrders = async () => {
  return prisma.order.findMany({
    include: {
      user: { select: { id: true, name: true, email: true } },
      orderItems: {
        include: {
          medicine: {
            include: { seller: { select: { id: true, name: true } } }
          }
        }
      }
    },
    orderBy: { createdAt: "desc" }
  });
};
var getDashboardStats = async () => {
  const totalUsers = await prisma.user.count();
  const totalMedicines = await prisma.medicine.count();
  const totalOrders = await prisma.order.count();
  return {
    totalUsers,
    totalMedicines,
    totalOrders
  };
};
var adminServices = {
  getAllUsers,
  updateUserStatus,
  getAllMedicines: getAllMedicines3,
  deleteMedicineByAdmin,
  getAllOrders,
  getDashboardStats
};

// src/modules/admin/admin.controller.ts
var getUsers = async (_req, res, next) => {
  try {
    const users = await adminServices.getAllUsers();
    res.status(200).json({ success: true, data: users });
  } catch (error) {
    next(error);
  }
};
var changeUserStatus = async (req, res, next) => {
  try {
    const { id } = req.params;
    const { status } = req.body;
    const user = await adminServices.updateUserStatus(id, status);
    res.status(200).json({ success: true, data: user });
  } catch (error) {
    next(error);
  }
};
var getMedicines = async (_req, res, next) => {
  try {
    const medicines = await adminServices.getAllMedicines();
    res.status(200).json({ success: true, data: medicines });
  } catch (error) {
    next(error);
  }
};
var removeMedicine = async (req, res, next) => {
  try {
    const { id } = req.params;
    const medicine = await adminServices.deleteMedicineByAdmin(id);
    res.status(200).json({ success: true, data: medicine });
  } catch (error) {
    next(error);
  }
};
var getOrders = async (_req, res, next) => {
  try {
    const orders = await adminServices.getAllOrders();
    res.status(200).json({ success: true, data: orders });
  } catch (error) {
    next(error);
  }
};
var getStats = async (req, res) => {
  const stats = await adminServices.getDashboardStats();
  res.status(200).json({
    success: true,
    data: stats
  });
};
var adminController = {
  getUsers,
  changeUserStatus,
  getMedicines,
  removeMedicine,
  getOrders,
  getStats
};

// src/modules/admin/admin.route.ts
var router7 = express6.Router();
router7.use(auth_default("ADMIN" /* ADMIN */));
router7.get("/users", adminController.getUsers);
router7.patch("/users/:id", adminController.changeUserStatus);
router7.get("/medicines", adminController.getMedicines);
router7.delete("/medicines/:id", adminController.removeMedicine);
router7.get("/orders", adminController.getOrders);
router7.get("/stats", adminController.getStats);
var adminRouter = router7;

// src/app.ts
var app = express7();
app.use(
  cors({
    origin: process.env.APP_URL || "http://localhost:3000",
    credentials: true
  })
);
app.use(express7.json());
app.all("/api/auth/*splat", toNodeHandler(auth));
app.use("/medicine", medicineRouter);
app.use("/category", categoryRouter);
app.use("/orders", orderRouter);
app.use("/cart", cartRouter);
app.use("/seller/orders", sellerOrderRouter);
app.use("/review", reviewRouter);
app.use("/admin", adminRouter);
app.get("/", (req, res) => {
  res.send("Hello, World!");
});
app.use(notFound);
app.use(globalErrorHandler_default);
var app_default = app;

// src/index.ts
var index_default = app_default;
export {
  index_default as default
};
